## Foundations for efficiencies

### Built-in practice: range()

In [1]:
# Create a range object that goes from 0 to 5
nums = range(6)
print(type(nums))

# Convert nums to a list
nums_list =list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,13,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]

### Built-in practice: enumerate()

In [2]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [3]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i, name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]

### Built-in practice: map()

In [4]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

### Bringing it all together: Festivus!

In [22]:
def welcome_guest(guest_and_time):
    """
    Returns a welcome string for the guest_and_time tuple.
    
    Args:
        guest_and_time (tuple): The guest and time tuple to create
            a welcome string for.
            
    Returns:
        welcome_string (str): A string welcoming the guest to Festivus.
        'Welcome to Festivus {guest}... You're {time} min late.'
    
    """
    guest = guest_and_time[0]
    arrival_time = guest_and_time[1]
    welcome_string = "Welcome to Festivus {}... You're {} min late.".format(guest,arrival_time)
    return welcome_string

In [23]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

print(names)

Welcome to Festivus Jerry... You're 7 min late.
Welcome to Festivus Kramer... You're 17 min late.
Welcome to Festivus Elaine... You're 27 min late.
Welcome to Festivus George... You're 37 min late.
Welcome to Festivus Newman... You're 47 min late.
['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

## Gaining efficiencies

### Combining Pokémon names and types

In [24]:
names = ['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl', 'Aggron', 'Aipom', 'Alakazam', 'Alomomola', 'Altaria']
primary_types = ['Grass', 'Psychic', 'Dark', 'Bug', 'Rock', 'Steel', 'Normal', 'Psychic', 'Water', 'Dragon']

# Combine names and primary_types
names_type1 = [*zip(names, primary_types)]

print(*names_type1[:5], sep='\n')

('Abomasnow', 'Grass')
('Abra', 'Psychic')
('Absol', 'Dark')
('Accelgor', 'Bug')
('Aerodactyl', 'Rock')

### Counting Pokémon from a sample

In [26]:
from collections import Counter
# Collect the count of primary types
type_count = Counter(primary_types)
print(type_count, '\n')

Counter({'Psychic': 2, 'Grass': 1, 'Dark': 1, 'Bug': 1, 'Rock': 1, 'Steel': 1, 'Normal': 1, 'Water': 1, 'Dragon': 1})

### Combinations of Pokémon

In [28]:
# Import combinations from itertools
from itertools import combinations

pokemon = ['Geodude', 'Cubone', 'Lickitung', 'Persian', 'Diglett']
# Create a combination object with pairs of Pokémon
combos_obj = combinations(pokemon, 2)
print(type(combos_obj), '\n')

# Convert combos_obj to a list by unpacking
combos_2 = [*combos_obj]
print(combos_2, '\n')

# Collect all possible combinations of 4 Pokémon directly into a list
combos_4 = [*combinations(pokemon, 4)]
print(combos_4)

<class 'itertools.combinations'>

[('Geodude', 'Cubone'), ('Geodude', 'Lickitung'), ('Geodude', 'Persian'), ('Geodude', 'Diglett'), ('Cubone', 'Lickitung'), ('Cubone', 'Persian'), ('Cubone', 'Diglett'), ('Lickitung', 'Persian'), ('Lickitung', 'Diglett'), ('Persian', 'Diglett')]

[('Geodude', 'Cubone', 'Lickitung', 'Persian'), ('Geodude', 'Cubone', 'Lickitung', 'Diglett'), ('Geodude', 'Cubone', 'Persian', 'Diglett'), ('Geodude', 'Lickitung', 'Persian', 'Diglett'), ('Cubone', 'Lickitung', 'Persian', 'Diglett')]

### Comparing Pokédexes

In [29]:
ash_pokedex = ['Pikachu', 'Bulbasaur', 'Koffing', 'Spearow', 'Vulpix', 'Wigglytuff', 'Zubat', 'Rattata', 'Psyduck', 'Squirtle']
misty_pokedex = ['Krabby', 'Horsea', 'Slowbro', 'Tentacool', 'Vaporeon', 'Magikarp', 'Poliwag', 'Starmie', 'Psyduck', 'Squirtle']
# Convert both lists to sets
ash_set = set(ash_pokedex)
misty_set = set(misty_pokedex)

# Find the Pokémon that exist in both sets
both = ash_set.intersection(misty_set)
print(both)

# Find the Pokémon that Ash has and Misty does not have
ash_only = ash_set.difference(misty_set)
print(ash_only)

# Find the Pokémon that are in only one set (not both)
unique_to_set = ash_set.symmetric_difference(misty_set)
print(unique_to_set)

{'Psyduck', 'Squirtle'}
{'Spearow', 'Vulpix', 'Koffing', 'Rattata', 'Bulbasaur', 'Pikachu', 'Zubat', 'Wigglytuff'}
{'Tentacool', 'Poliwag', 'Slowbro', 'Vaporeon', 'Spearow', 'Vulpix', 'Zubat', 'Starmie', 'Krabby', 'Koffing', 'Rattata', 'Bulbasaur', 'Horsea', 'Pikachu', 'Magikarp', 'Wigglytuff'}

### Searching for Pokémon

In [30]:
print('Psyduck' in ash_set)

True

### Gathering unique Pokémon

In [32]:
set(pokemon)

{'Cubone', 'Diglett', 'Geodude', 'Lickitung', 'Persian'}

### Gathering Pokémon without a loop

In [34]:
poke_names = ['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl', 'Aggron', 'Aipom', 'Alakazam', 'Alomomola', 'Altaria']
poke_gens = [4, 1, 3, 5, 1, 3, 2, 1, 5, 3]

# Collect Pokémon that belong to generation 1 or generation 2
gen1_gen2_pokemon = [name for name,gen in zip(poke_names, poke_gens) if gen < 3]

# Create a map object that stores the name lengths
name_lengths_map = map(len, gen1_gen2_pokemon)

# Combine gen1_gen2_pokemon and name_lengths_map into a list
gen1_gen2_name_lengths = [*zip(gen1_gen2_pokemon, name_lengths_map)]

print(gen1_gen2_name_lengths[:5])

[('Abra', 4), ('Aerodactyl', 10), ('Aipom', 5), ('Alakazam', 8)]

### Pokémon totals and averages without a loop

In [39]:
import numpy as np
stats = np.array([np.array([90, 92, 75, 92, 85, 60]), np.array([ 25,  20,  15, 105,  55,  90]), np.array([ 65, 130,  60,  75,  60,  75]), np.array([ 80,  70,  40, 100,  60, 145]), np.array([ 80, 105,  65,  60,  75, 130])])
names = ['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl']

In [40]:
# Create a total stats array
total_stats_np = stats.sum(axis=1)

# Create an average stats array
avg_stats_np = stats.mean(axis = 1)

# Combine names, total_stats_np, and avg_stats_np into a list
poke_list_np = [*zip(names, total_stats_np, avg_stats_np)]

top_3 = sorted(poke_list_np, key=lambda x: x[1], reverse=True)[:3]
print('3 strongest Pokémon:\n{}'.format(top_3))

3 strongest Pokémon:
[('Aerodactyl', 515, 85.83333333333333), ('Accelgor', 495, 82.5), ('Abomasnow', 494, 82.33333333333333)]

### One-time calculation loop

In [42]:
# Import Counter
from collections import Counter

generations = [4, 1, 3, 5, 1, 3, 2, 1, 5, 3, 6, 4, 5, 2, 3, 1, 1, 4, 5, 5]
# Collect the count of each generation
gen_counts = Counter(generations)

# Improve for loop by moving one calculation above the loop
total_count = len(generations)

for gen,count in gen_counts.items():
    gen_percent = round(count / total_count * 100, 2)
    print('generation {}: count = {:3} percentage = {}'
          .format(gen, count, gen_percent))

generation 4: count =   3 percentage = 15.0
generation 1: count =   5 percentage = 25.0
generation 3: count =   4 percentage = 20.0
generation 5: count =   5 percentage = 25.0
generation 2: count =   2 percentage = 10.0
generation 6: count =   1 percentage = 5.0

### Holistic conversion loop

In [44]:
pokemon_types = ['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire', 'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison', 'Psychic', 'Rock', 'Steel', 'Water']

In [45]:
# Collect all possible pairs using combinations()
possible_pairs = [*combinations(pokemon_types, 2)]

# Create an empty list called enumerated_tuples
enumerated_tuples = []

# Add a line to append each enumerated_pair_tuple to the empty list above
for i,pair in enumerate(possible_pairs, 1):
    enumerated_pair_tuple = (i,) + pair
    enumerated_tuples.append(enumerated_pair_tuple)

# Convert all tuples in enumerated_tuples to a list
enumerated_pairs = [*map(list, enumerated_tuples)]
print(enumerated_pairs)

[[1, 'Bug', 'Dark'], [2, 'Bug', 'Dragon'], [3, 'Bug', 'Electric'], [4, 'Bug', 'Fairy'], [5, 'Bug', 'Fighting'], [6, 'Bug', 'Fire'], [7, 'Bug', 'Flying'], [8, 'Bug', 'Ghost'], [9, 'Bug', 'Grass'], [10, 'Bug', 'Ground'], [11, 'Bug', 'Ice'], [12, 'Bug', 'Normal'], [13, 'Bug', 'Poison'], [14, 'Bug', 'Psychic'], [15, 'Bug', 'Rock'], [16, 'Bug', 'Steel'], [17, 'Bug', 'Water'], [18, 'Dark', 'Dragon'], [19, 'Dark', 'Electric'], [20, 'Dark', 'Fairy'], [21, 'Dark', 'Fighting'], [22, 'Dark', 'Fire'], [23, 'Dark', 'Flying'], [24, 'Dark', 'Ghost'], [25, 'Dark', 'Grass'], [26, 'Dark', 'Ground'], [27, 'Dark', 'Ice'], [28, 'Dark', 'Normal'], [29, 'Dark', 'Poison'], [30, 'Dark', 'Psychic'], [31, 'Dark', 'Rock'], [32, 'Dark', 'Steel'], [33, 'Dark', 'Water'], [34, 'Dragon', 'Electric'], [35, 'Dragon', 'Fairy'], [36, 'Dragon', 'Fighting'], [37, 'Dragon', 'Fire'], [38, 'Dragon', 'Flying'], [39, 'Dragon', 'Ghost'], [40, 'Dragon', 'Grass'], [41, 'Dragon', 'Ground'], [42, 'Dragon', 'Ice'], [43, 'Dragon', 'Normal'], [44, 'Dragon', 'Poison'], [45, 'Dragon', 'Psychic'], [46, 'Dragon', 'Rock'], [47, 'Dragon', 'Steel'], [48, 'Dragon', 'Water'], [49, 'Electric', 'Fairy'], [50, 'Electric', 'Fighting'], [51, 'Electric', 'Fire'], [52, 'Electric', 'Flying'], [53, 'Electric', 'Ghost'], [54, 'Electric', 'Grass'], [55, 'Electric', 'Ground'], [56, 'Electric', 'Ice'], [57, 'Electric', 'Normal'], [58, 'Electric', 'Poison'], [59, 'Electric', 'Psychic'], [60, 'Electric', 'Rock'], [61, 'Electric', 'Steel'], [62, 'Electric', 'Water'], [63, 'Fairy', 'Fighting'], [64, 'Fairy', 'Fire'], [65, 'Fairy', 'Flying'], [66, 'Fairy', 'Ghost'], [67, 'Fairy', 'Grass'], [68, 'Fairy', 'Ground'], [69, 'Fairy', 'Ice'], [70, 'Fairy', 'Normal'], [71, 'Fairy', 'Poison'], [72, 'Fairy', 'Psychic'], [73, 'Fairy', 'Rock'], [74, 'Fairy', 'Steel'], [75, 'Fairy', 'Water'], [76, 'Fighting', 'Fire'], [77, 'Fighting', 'Flying'], [78, 'Fighting', 'Ghost'], [79, 'Fighting', 'Grass'], [80, 'Fighting', 'Ground'], [81, 'Fighting', 'Ice'], [82, 'Fighting', 'Normal'], [83, 'Fighting', 'Poison'], [84, 'Fighting', 'Psychic'], [85, 'Fighting', 'Rock'], [86, 'Fighting', 'Steel'], [87, 'Fighting', 'Water'], [88, 'Fire', 'Flying'], [89, 'Fire', 'Ghost'], [90, 'Fire', 'Grass'], [91, 'Fire', 'Ground'], [92, 'Fire', 'Ice'], [93, 'Fire', 'Normal'], [94, 'Fire', 'Poison'], [95, 'Fire', 'Psychic'], [96, 'Fire', 'Rock'], [97, 'Fire', 'Steel'], [98, 'Fire', 'Water'], [99, 'Flying', 'Ghost'], [100, 'Flying', 'Grass'], [101, 'Flying', 'Ground'], [102, 'Flying', 'Ice'], [103, 'Flying', 'Normal'], [104, 'Flying', 'Poison'], [105, 'Flying', 'Psychic'], [106, 'Flying', 'Rock'], [107, 'Flying', 'Steel'], [108, 'Flying', 'Water'], [109, 'Ghost', 'Grass'], [110, 'Ghost', 'Ground'], [111, 'Ghost', 'Ice'], [112, 'Ghost', 'Normal'], [113, 'Ghost', 'Poison'], [114, 'Ghost', 'Psychic'], [115, 'Ghost', 'Rock'], [116, 'Ghost', 'Steel'], [117, 'Ghost', 'Water'], [118, 'Grass', 'Ground'], [119, 'Grass', 'Ice'], [120, 'Grass', 'Normal'], [121, 'Grass', 'Poison'], [122, 'Grass', 'Psychic'], [123, 'Grass', 'Rock'], [124, 'Grass', 'Steel'], [125, 'Grass', 'Water'], [126, 'Ground', 'Ice'], [127, 'Ground', 'Normal'], [128, 'Ground', 'Poison'], [129, 'Ground', 'Psychic'], [130, 'Ground', 'Rock'], [131, 'Ground', 'Steel'], [132, 'Ground', 'Water'], [133, 'Ice', 'Normal'], [134, 'Ice', 'Poison'], [135, 'Ice', 'Psychic'], [136, 'Ice', 'Rock'], [137, 'Ice', 'Steel'], [138, 'Ice', 'Water'], [139, 'Normal', 'Poison'], [140, 'Normal', 'Psychic'], [141, 'Normal', 'Rock'], [142, 'Normal', 'Steel'], [143, 'Normal', 'Water'], [144, 'Poison', 'Psychic'], [145, 'Poison', 'Rock'], [146, 'Poison', 'Steel'], [147, 'Poison', 'Water'], [148, 'Psychic', 'Rock'], [149, 'Psychic', 'Steel'], [150, 'Psychic', 'Water'], [151, 'Rock', 'Steel'], [152, 'Rock', 'Water'], [153, 'Steel', 'Water']]

### Bringing it all together: Pokémon z-scores

In [46]:
hps = np.array([80.0, 60.0, 131.0, 62.0, 71.0, 109.0, 45.0, 53.0, 73.0, 60.0])
names = ['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl', 'Aggron', 'Aipom', 'Alakazam', 'Alomomola', 'Altaria']

# Calculate the total HP avg and total HP standard deviation
hp_avg = hps.mean()
hp_std = hps.std()

# Use NumPy to eliminate the previous for loop
z_scores = (hps - hp_avg)/hp_std

# Combine names, hps, and z_scores
poke_zscores2 = [*zip(names, hps, z_scores)]
print(*poke_zscores2[:3], sep='\n')

# Use list comprehension with the same logic as the highest_hp_pokemon code block
highest_hp_pokemon = [(name,hp,zscore) for name,hp,zscore in poke_zscores2 if zscore > 2]
print(*highest_hp_pokemon, sep='\n')

('Abomasnow', 80.0, 0.22246758193284516)
('Abra', 60.0, -0.5720594963987454)
('Absol', 131.0, 2.2485116316784013)
('Absol', 131.0, 2.2485116316784013)

### Basic pandas optimizations

### Iterating with .iterrows()

In [50]:
import pandas as pd
pit_df = pd.read_csv('baseball_stats.csv')
pit_df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424

In [48]:
# Iterate over pit_df and print each index variable and then each row
for i,row in pit_df.iterrows():
    print(i)
    print(row)
    print(type(row))

0
Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
1
Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
Name: 1, dtype: object
<class 'pandas.core.series.Series'>
2
Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
Name: 2, dtype: object
<class 'pandas.core.series.Series'>
3
Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
Name: 3, dtype: object
<class 'pandas.core.series.Series'>
4
Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
Name: 4, dtype: object
<class 'pandas.core.series.Series'>
5
Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
Name: 5, dtype: object
<class 'pandas.core.series.Series'>
6
Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
Name: 6, dtype: object
<class 'pandas.core.series.Series'>
7
Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
Name: 7, dtype: object
<class 'pandas.core.series.Series'>
8
Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
Name: 8, dtype: object
<class 'pandas.core.series.Series'>
9
Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
Name: 9, dtype: object
<class 'pandas.core.series.Series'>
10
Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
Name: 10, dtype: object
<class 'pandas.core.series.Series'>
11
Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
Name: 11, dtype: object
<class 'pandas.core.series.Series'>
12
Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
Name: 12, dtype: object
<class 'pandas.core.series.Series'>
13
Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
Name: 13, dtype: object
<class 'pandas.core.series.Series'>
14
Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
Name: 14, dtype: object
<class 'pandas.core.series.Series'>
15
Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
Name: 15, dtype: object
<class 'pandas.core.series.Series'>
16
Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
Name: 16, dtype: object
<class 'pandas.core.series.Series'>
17
Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
Name: 17, dtype: object
<class 'pandas.core.series.Series'>
18
Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
Name: 18, dtype: object
<class 'pandas.core.series.Series'>
19
Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
Name: 19, dtype: object
<class 'pandas.core.series.Series'>
20
Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
Name: 20, dtype: object
<class 'pandas.core.series.Series'>
21
Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
Name: 21, dtype: object
<class 'pandas.core.series.Series'>
22
Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
Name: 22, dtype: object
<class 'pandas.core.series.Series'>
23
Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
Name: 23, dtype: object
<class 'pandas.core.series.Series'>
24
Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
Name: 24, dtype: object
<class 'pandas.core.series.Series'>
25
Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
Name: 25, dtype: object
<class 'pandas.core.series.Series'>
26
Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
Name: 26, dtype: object
<class 'pandas.core.series.Series'>
27
Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
Name: 27, dtype: object
<class 'pandas.core.series.Series'>
28
Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
Name: 28, dtype: object
<class 'pandas.core.series.Series'>
29
Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
Name: 29, dtype: object
<class 'pandas.core.series.Series'>
30
Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
Name: 30, dtype: object
<class 'pandas.core.series.Series'>
31
Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
Name: 31, dtype: object
<class 'pandas.core.series.Series'>
32
Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
Name: 32, dtype: object
<class 'pandas.core.series.Series'>
33
Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
Name: 33, dtype: object
<class 'pandas.core.series.Series'>
34
Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
Name: 34, dtype: object
<class 'pandas.core.series.Series'>
35
Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
Name: 35, dtype: object
<class 'pandas.core.series.Series'>
36
Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
Name: 36, dtype: object
<class 'pandas.core.series.Series'>
37
Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
Name: 37, dtype: object
<class 'pandas.core.series.Series'>
38
Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
Name: 38, dtype: object
<class 'pandas.core.series.Series'>
39
Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
Name: 39, dtype: object
<class 'pandas.core.series.Series'>
40
Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
Name: 40, dtype: object
<class 'pandas.core.series.Series'>
41
Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
Name: 41, dtype: object
<class 'pandas.core.series.Series'>
42
Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
Name: 42, dtype: object
<class 'pandas.core.series.Series'>
43
Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
Name: 43, dtype: object
<class 'pandas.core.series.Series'>
44
Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
Name: 44, dtype: object
<class 'pandas.core.series.Series'>
45
Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.304
OSLG            0.385
Name: 45, dtype: object
<class 'pandas.core.series.Series'>
46
Team              MIN
League             AL
Year             2011
RS                619
RA                804
W                  63
OBP             0.306
SLG              0.36
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.435
Name: 46, dtype: object
<class 'pandas.core.series.Series'>
47
Team              NYM
League             NL
Year             2011
RS                718
RA                742
W                  77
OBP             0.335
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.411
Name: 47, dtype: object
<class 'pandas.core.series.Series'>
48
Team              NYY
League             AL
Year             2011
RS                867
RA                657
W                  97
OBP             0.343
SLG             0.444
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
Name: 48, dtype: object
<class 'pandas.core.series.Series'>
49
Team              OAK
League             AL
Year             2011
RS                645
RA                679
W                  74
OBP             0.311
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.378
Name: 49, dtype: object
<class 'pandas.core.series.Series'>
50
Team              PHI
League             NL
Year             2011
RS                713
RA                529
W                 102
OBP             0.323
SLG             0.395
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.296
OSLG            0.361
Name: 50, dtype: object

Name: 248, dtype: object
<class 'pandas.core.series.Series'>
249
Team              COL
League             NL
Year             2004
RS                833
RA                923
W                  68
OBP             0.345
SLG             0.455
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.372
OSLG            0.471
Name: 249, dtype: object
<class 'pandas.core.series.Series'>
250
Team              DET
League             AL
Year             2004
RS                827
RA                844
W                  72
OBP             0.337
SLG             0.449
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.441
Name: 250, dtype: object
<class 'pandas.core.series.Series'>
251
Team              FLA
League             NL
Year             2004
RS                718
RA                700
W                  83
OBP             0.329
SLG             0.406
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.324
OSLG            0.412
Name: 251, dtype: object
<class 'pandas.core.series.Series'>
252
Team              HOU
League             NL
Year             2004
RS                803
RA                698
W                  92
OBP             0.342
SLG             0.436
BA              0.267
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.328
OSLG            0.417
Name: 252, dtype: object
<class 'pandas.core.series.Series'>
253
Team              KCR
League             AL
Year             2004
RS                720
RA                905
W                  58
OBP             0.322
SLG             0.397
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.476
Name: 253, dtype: object
<class 'pandas.core.series.Series'>
254
Team              LAD
League             NL
Year             2004
RS                761
RA                684
W                  93
OBP             0.332
SLG             0.423
BA              0.262
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.323
OSLG            0.408
Name: 254, dtype: object
<class 'pandas.core.series.Series'>
255
Team              MIL
League             NL
Year             2004
RS                634
RA                757
W                  67
OBP             0.321
SLG             0.387
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.32
OSLG            0.417
Name: 255, dtype: object
<class 'pandas.core.series.Series'>
256
Team              MIN
League             AL
Year             2004
RS                780
RA                715
W                  92
OBP             0.332
SLG             0.431
BA              0.266
Playoffs            1
RankSeason          6
RankPlayoffs        4
G                 162
OOBP            0.323
OSLG            0.406
Name: 256, dtype: object
<class 'pandas.core.series.Series'>
257
Team              MON
League             NL
Year             2004
RS                635
RA                769
W                  67
OBP             0.313
SLG             0.392
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.342
OSLG            0.431
Name: 257, dtype: object
<class 'pandas.core.series.Series'>
258
Team              NYM
League             NL
Year             2004
RS                684
RA                731
W                  71
OBP             0.317
SLG             0.409
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.405
Name: 258, dtype: object
<class 'pandas.core.series.Series'>
259
Team              NYY
League             AL
Year             2004
RS                897
RA                808
W                 101
OBP             0.353
SLG             0.458
BA              0.268
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP            0.328
OSLG            0.432
Name: 259, dtype: object
<class 'pandas.core.series.Series'>
260
Team              OAK
League             AL
Year             2004
RS                793
RA                742
W                  91
OBP             0.343
SLG             0.433
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.409
Name: 260, dtype: object
<class 'pandas.core.series.Series'>
261
Team              PHI
League             NL
Year             2004
RS                840
RA                781
W                  86
OBP             0.345
SLG             0.443
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.33
OSLG            0.448
Name: 261, dtype: object
<class 'pandas.core.series.Series'>
262
Team              PIT
League             NL
Year             2004
RS                680
RA                744
W                  72
OBP             0.321
SLG             0.401
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.342
OSLG            0.416
Name: 262, dtype: object
<class 'pandas.core.series.Series'>
263
Team              SDP
League             NL
Year             2004
RS                768
RA                705
W                  87
OBP             0.342
SLG             0.414
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.318
OSLG            0.431
Name: 263, dtype: object
<class 'pandas.core.series.Series'>
264
Team              SEA
League             AL
Year             2004
RS                698
RA                823
W                  63
OBP             0.331
SLG             0.396
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.441
Name: 264, dtype: object
<class 'pandas.core.series.Series'>
265
Team              SFG
League             NL
Year             2004
RS                850
RA                770
W                  91
OBP             0.357
SLG             0.438
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.423
Name: 265, dtype: object
<class 'pandas.core.series.Series'>
266
Team              STL
League             NL
Year             2004
RS                855
RA                659
W                 105
OBP             0.344
SLG              0.46
BA              0.278
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP            0.313
OSLG            0.403
Name: 266, dtype: object
<class 'pandas.core.series.Series'>
267
Team              TBD
League             AL
Year             2004
RS                714
RA                842
W                  70
OBP              0.32
SLG             0.405
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.342
OSLG            0.438
Name: 267, dtype: object
<class 'pandas.core.series.Series'>
268
Team              TEX
League             AL
Year             2004
RS                860
RA                794
W                  89
OBP             0.329
SLG             0.457
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.344
OSLG            0.432
Name: 268, dtype: object
<class 'pandas.core.series.Series'>
269
Team              TOR
League             AL
Year             2004
RS                719
RA                823
W                  67
OBP             0.328
SLG             0.403
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.348
OSLG            0.434
Name: 269, dtype: object
<class 'pandas.core.series.Series'>
270
Team              ANA
League             AL
Year             2003
RS                736
RA                743
W                  77
OBP              0.33
SLG             0.413
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.421
Name: 270, dtype: object
<class 'pandas.core.series.Series'>
271
Team              ARI
League             NL
Year             2003
RS                717
RA                685
W                  84
OBP              0.33
SLG             0.417
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.388
Name: 271, dtype: object
<class 'pandas.core.series.Series'>
272
Team              ATL
League             NL
Year             2003
RS                907
RA                740
W                 101
OBP             0.349
SLG             0.475
BA              0.284
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.327
OSLG            0.401
Name: 272, dtype: object
<class 'pandas.core.series.Series'>
273
Team              BAL
League             AL
Year             2003
RS                743
RA                820
W                  71
OBP             0.323
SLG             0.405
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP            0.346
OSLG            0.446
Name: 273, dtype: object
<class 'pandas.core.series.Series'>
274
Team              BOS
League             AL
Year             2003
RS                961
RA                809
W                  95
OBP              0.36
SLG             0.491
BA              0.289
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.327
OSLG            0.415
Name: 274, dtype: object
<class 'pandas.core.series.Series'>
275
Team              CHC
League             NL
Year             2003
RS                724
RA                683
W                  88
OBP             0.323
SLG             0.416
BA              0.259
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 162
OOBP            0.324
OSLG            0.372
Name: 275, dtype: object
<class 'pandas.core.series.Series'>
276
Team              CHW
League             AL
Year             2003
RS                791
RA                715
W                  86
OBP             0.331
SLG             0.446
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.404
Name: 276, dtype: object
<class 'pandas.core.series.Series'>
277
Team              CIN
League             NL
Year             2003
RS                694
RA                886
W                  69
OBP             0.318
SLG             0.395
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.349
OSLG            0.463
Name: 277, dtype: object
<class 'pandas.core.series.Series'>
278
Team              CLE
League             AL
Year             2003
RS                699
RA                778
W                  68
OBP             0.316
SLG             0.401
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.426
Name: 278, dtype: object
<class 'pandas.core.series.Series'>
279
Team              COL
League             NL
Year             2003
RS                853
RA                892
W                  74
OBP             0.344
SLG             0.445
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.359
OSLG             0.47
Name: 279, dtype: object
<class 'pandas.core.series.Series'>
280
Team              DET
League             AL
Year             2003
RS                591
RA                928
W                  43
OBP               0.3
SLG             0.375
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.461
Name: 280, dtype: object
<class 'pandas.core.series.Series'>
281
Team              FLA
League             NL
Year             2003
RS                751
RA                692
W                  91
OBP             0.333
SLG             0.421
BA              0.266
Playoffs            1
RankSeason          5
RankPlayoffs        1
G                 162
OOBP            0.325
OSLG            0.396
Name: 281, dtype: object
<class 'pandas.core.series.Series'>
282
Team              HOU
League             NL
Year             2003
RS                805
RA                677
W                  87
OBP             0.336
SLG             0.431
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.397
Name: 282, dtype: object
<class 'pandas.core.series.Series'>
283
Team              KCR
League             AL
Year             2003
RS                836
RA                867
W                  83
OBP             0.336
SLG             0.427
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG             0.45
Name: 283, dtype: object
<class 'pandas.core.series.Series'>
284
Team              LAD
League             NL
Year             2003
RS                574
RA                556
W                  85
OBP             0.303
SLG             0.368
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.354
Name: 284, dtype: object
<class 'pandas.core.series.Series'>
285
Team              MIL
League             NL
Year             2003
RS                714
RA                873
W                  68
OBP             0.329
SLG             0.419
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.462
Name: 285, dtype: object
<class 'pandas.core.series.Series'>
286
Team              MIN
League             AL
Year             2003
RS                801
RA                758
W                  90
OBP             0.341
SLG             0.431
BA              0.277
Playoffs            1
RankSeason          6
RankPlayoffs        4
G                 162
OOBP            0.319
OSLG            0.428
Name: 286, dtype: object
<class 'pandas.core.series.Series'>
287
Team              MON
League             NL
Year             2003
RS                711
RA                716
W                  83
OBP             0.326
SLG             0.401
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.423
Name: 287, dtype: object
<class 'pandas.core.series.Series'>
288
Team              NYM
League             NL
Year             2003
RS                642
RA                754
W                  66
OBP             0.314
SLG             0.374
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.345
OSLG            0.438
Name: 288, dtype: object
<class 'pandas.core.series.Series'>
289
Team              NYY
League             AL
Year             2003
RS                877
RA                716
W                 101
OBP             0.356
SLG             0.453
BA              0.271
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 163
OOBP            0.314
OSLG            0.407
Name: 289, dtype: object
<class 'pandas.core.series.Series'>
290
Team              OAK
League             AL
Year             2003
RS                768
RA                643
W                  96
OBP             0.327
SLG             0.417
BA              0.254
Playoffs            1
RankSeason          3
RankPlayoffs        4
G                 162
OOBP            0.314
OSLG            0.376
Name: 290, dtype: object
<class 'pandas.core.series.Series'>
291
Team              PHI
League             NL
Year             2003
RS                791
RA                697
W                  86
OBP             0.343
SLG             0.419
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.401
Name: 291, dtype: object
<class 'pandas.core.series.Series'>
292
Team              PIT
League             NL
Year             2003
RS                753
RA                801
W                  75
OBP             0.338
SLG              0.42
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.431
Name: 292, dtype: object
<class 'pandas.core.series.Series'>
293
Team              SDP
League             NL
Year             2003
RS                678
RA                831
W                  64
OBP             0.333
SLG             0.388
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG            0.437
Name: 293, dtype: object
<class 'pandas.core.series.Series'>
294
Team              SEA
League             AL
Year             2003
RS                795
RA                637
W                  93
OBP             0.344
SLG              0.41
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.311
OSLG            0.388
Name: 294, dtype: object
<class 'pandas.core.series.Series'>
295
Team              SFG
League             NL
Year             2003
RS                755
RA                638
W                 100
OBP             0.338
SLG             0.425
BA              0.264
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 161
OOBP            0.321
OSLG            0.386
Name: 295, dtype: object
<class 'pandas.core.series.Series'>
296
Team              STL
League             NL
Year             2003
RS                876
RA                796
W                  85
OBP              0.35
SLG             0.454
BA              0.279
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.452
Name: 296, dtype: object
<class 'pandas.core.series.Series'>
297
Team              TBD
League             AL
Year             2003
RS                715
RA                852
W                  63
OBP              0.32
SLG             0.404
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.347
OSLG             0.44
Name: 297, dtype: object
<class 'pandas.core.series.Series'>
298
Team              TEX
League             AL
Year             2003
RS                826
RA                969
W                  71
OBP              0.33
SLG             0.454
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.36
OSLG            0.473
Name: 298, dtype: object
<class 'pandas.core.series.Series'>
299
Team              TOR
League             AL
Year             2003
RS                894
RA                826
W                  86
OBP             0.349
SLG             0.455

Name: 442, dtype: object
<class 'pandas.core.series.Series'>
443
Team              SDP
League             NL
Year             1998
RS                749
RA                635
W                  98
OBP              0.33
SLG             0.409
BA              0.253
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 443, dtype: object
<class 'pandas.core.series.Series'>
444
Team              SEA
League             AL
Year             1998
RS                859
RA                855
W                  76
OBP             0.345
SLG             0.468
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 444, dtype: object
<class 'pandas.core.series.Series'>
445
Team              SFG
League             NL
Year             1998
RS                845
RA                739
W                  89
OBP             0.353
SLG             0.421
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 445, dtype: object
<class 'pandas.core.series.Series'>
446
Team              STL
League             NL
Year             1998
RS                810
RA                782
W                  83
OBP             0.341
SLG             0.441
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 446, dtype: object
<class 'pandas.core.series.Series'>
447
Team              TBD
League             AL
Year             1998
RS                620
RA                751
W                  63
OBP             0.321
SLG             0.385
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 447, dtype: object
<class 'pandas.core.series.Series'>
448
Team              TEX
League             AL
Year             1998
RS                940
RA                871
W                  88
OBP             0.357
SLG             0.462
BA              0.289
Playoffs            1
RankSeason          8
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 448, dtype: object
<class 'pandas.core.series.Series'>
449
Team              TOR
League             AL
Year             1998
RS                816
RA                768
W                  88
OBP              0.34
SLG             0.448
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 449, dtype: object
<class 'pandas.core.series.Series'>
450
Team              ANA
League             AL
Year             1997
RS                829
RA                794
W                  84
OBP             0.346
SLG             0.416
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 450, dtype: object
<class 'pandas.core.series.Series'>
451
Team              ATL
League             NL
Year             1997
RS                791
RA                581
W                 101
OBP             0.343
SLG             0.426
BA               0.27
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 451, dtype: object
<class 'pandas.core.series.Series'>
452
Team              BAL
League             AL
Year             1997
RS                812
RA                681
W                  98
OBP             0.341
SLG             0.429
BA              0.268
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 452, dtype: object
<class 'pandas.core.series.Series'>
453
Team              BOS
League             AL
Year             1997
RS                851
RA                857
W                  78
OBP             0.352
SLG             0.463
BA              0.291
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 453, dtype: object
<class 'pandas.core.series.Series'>
454
Team              CHC
League             NL
Year             1997
RS                687
RA                759
W                  68
OBP             0.321
SLG             0.396
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 454, dtype: object
<class 'pandas.core.series.Series'>
455
Team              CHW
League             AL
Year             1997
RS                779
RA                833
W                  80
OBP             0.341
SLG             0.417
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 455, dtype: object
<class 'pandas.core.series.Series'>
456
Team              CIN
League             NL
Year             1997
RS                651
RA                764
W                  76
OBP             0.321
SLG             0.389
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 456, dtype: object
<class 'pandas.core.series.Series'>
457
Team              CLE
League             AL
Year             1997
RS                868
RA                815
W                  86
OBP             0.358
SLG             0.467
BA              0.286
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 161
OOBP              NaN
OSLG              NaN
Name: 457, dtype: object
<class 'pandas.core.series.Series'>
458
Team              COL
League             NL
Year             1997
RS                923
RA                908
W                  83
OBP             0.357
SLG             0.478
BA              0.288
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 458, dtype: object
<class 'pandas.core.series.Series'>
459
Team              DET
League             AL
Year             1997
RS                784
RA                790
W                  79
OBP             0.332
SLG             0.415
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 459, dtype: object
<class 'pandas.core.series.Series'>
460
Team              FLA
League             NL
Year             1997
RS                740
RA                669
W                  92
OBP             0.346
SLG             0.395
BA              0.259
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 460, dtype: object
<class 'pandas.core.series.Series'>
461
Team              HOU
League             NL
Year             1997
RS                777
RA                660
W                  84
OBP             0.344
SLG             0.403
BA              0.259
Playoffs            1
RankSeason          7
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 461, dtype: object
<class 'pandas.core.series.Series'>
462
Team              KCR
League             AL
Year             1997
RS                747
RA                820
W                  67
OBP             0.333
SLG             0.407
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 462, dtype: object
<class 'pandas.core.series.Series'>
463
Team              LAD
League             NL
Year             1997
RS                742
RA                645
W                  88
OBP              0.33
SLG             0.418
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 463, dtype: object
<class 'pandas.core.series.Series'>
464
Team              MIL
League             AL
Year             1997
RS                681
RA                742
W                  78
OBP             0.325
SLG             0.398
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 464, dtype: object
<class 'pandas.core.series.Series'>
465
Team              MIN
League             AL
Year             1997
RS                772
RA                861
W                  68
OBP             0.333
SLG             0.409
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 465, dtype: object
<class 'pandas.core.series.Series'>
466
Team              MON
League             NL
Year             1997
RS                691
RA                740
W                  78
OBP             0.316
SLG             0.425
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 466, dtype: object
<class 'pandas.core.series.Series'>
467
Team              NYM
League             NL
Year             1997
RS                777
RA                709
W                  88
OBP             0.332
SLG             0.405
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 467, dtype: object
<class 'pandas.core.series.Series'>
468
Team              NYY
League             AL
Year             1997
RS                891
RA                688
W                  96
OBP             0.362
SLG             0.436
BA              0.287
Playoffs            1
RankSeason          3
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 468, dtype: object
<class 'pandas.core.series.Series'>
469
Team              OAK
League             AL
Year             1997
RS                764
RA                946
W                  65
OBP             0.339
SLG             0.423
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 469, dtype: object
<class 'pandas.core.series.Series'>
470
Team              PHI
League             NL
Year             1997
RS                668
RA                840
W                  68
OBP             0.322
SLG             0.385
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 470, dtype: object
<class 'pandas.core.series.Series'>
471
Team              PIT
League             NL
Year             1997
RS                725
RA                760
W                  79
OBP             0.329
SLG             0.404
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 471, dtype: object
<class 'pandas.core.series.Series'>
472
Team              SDP
League             NL
Year             1997
RS                795
RA                891
W                  76
OBP             0.342
SLG             0.407
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 472, dtype: object
<class 'pandas.core.series.Series'>
473
Team              SEA
League             AL
Year             1997
RS                925
RA                833
W                  90
OBP             0.355
SLG             0.485
BA               0.28
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 473, dtype: object
<class 'pandas.core.series.Series'>
474
Team              SFG
League             NL
Year             1997
RS                784
RA                793
W                  90
OBP             0.337
SLG             0.414
BA              0.258
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 474, dtype: object
<class 'pandas.core.series.Series'>
475
Team              STL
League             NL
Year             1997
RS                689
RA                708
W                  73
OBP             0.324
SLG             0.396
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 475, dtype: object
<class 'pandas.core.series.Series'>
476
Team              TEX
League             AL
Year             1997
RS                807
RA                823
W                  77
OBP             0.334
SLG             0.438
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 476, dtype: object
<class 'pandas.core.series.Series'>
477
Team              TOR
League             AL
Year             1997
RS                654
RA                694
W                  76
OBP              0.31
SLG             0.389
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 477, dtype: object
<class 'pandas.core.series.Series'>
478
Team              ATL
League             NL
Year             1996
RS                773
RA                648
W                  96
OBP             0.333
SLG             0.432
BA               0.27
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 478, dtype: object
<class 'pandas.core.series.Series'>
479
Team              BAL
League             AL
Year             1996
RS                949
RA                903
W                  88
OBP              0.35
SLG             0.472
BA              0.274
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 163
OOBP              NaN
OSLG              NaN
Name: 479, dtype: object
<class 'pandas.core.series.Series'>
480
Team              BOS
League             AL
Year             1996
RS                928
RA                921
W                  85
OBP             0.359
SLG             0.457
BA              0.283
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 480, dtype: object
<class 'pandas.core.series.Series'>
481
Team              CAL
League             AL
Year             1996
RS                762
RA                943
W                  70
OBP             0.339
SLG             0.431
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 481, dtype: object
<class 'pandas.core.series.Series'>
482
Team              CHC
League             NL
Year             1996
RS                772
RA                771
W                  76
OBP              0.32
SLG             0.401
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 482, dtype: object
<class 'pandas.core.series.Series'>
483
Team              CHW
League             AL
Year             1996
RS                898
RA                794
W                  85
OBP              0.36
SLG             0.447
BA              0.281
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 483, dtype: object
<class 'pandas.core.series.Series'>
484
Team              CIN
League             NL
Year             1996
RS                778
RA                773
W                  81
OBP             0.331
SLG             0.422
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 484, dtype: object
<class 'pandas.core.series.Series'>
485
Team              CLE
League             AL
Year             1996
RS                952
RA                769
W                  99
OBP             0.369
SLG             0.475
BA              0.293
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 161
OOBP              NaN
OSLG              NaN
Name: 485, dtype: object
<class 'pandas.core.series.Series'>
486
Team              COL
League             NL
Year             1996
RS                961
RA                964
W                  83
OBP             0.355
SLG             0.472
BA              0.287
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 486, dtype: object
<class 'pandas.core.series.Series'>
487
Team              DET
League             AL
Year             1996
RS                783
RA               1103
W                  53
OBP             0.323
SLG              0.42
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 487, dtype: object
<class 'pandas.core.series.Series'>
488
Team              FLA
League             NL
Year             1996
RS                688
RA                703
W                  80
OBP             0.329
SLG             0.393
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 488, dtype: object
<class 'pandas.core.series.Series'>
489
Team              HOU
League             NL
Year             1996
RS                753
RA                792
W                  82
OBP             0.336
SLG             0.397
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 489, dtype: object
<class 'pandas.core.series.Series'>
490
Team              KCR
League             AL
Year             1996
RS                746
RA                786
W                  75
OBP             0.332
SLG             0.398
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 490, dtype: object
<class 'pandas.core.series.Series'>
491
Team              LAD
League             NL
Year             1996
RS                703
RA                652
W                  90
OBP             0.316
SLG             0.384
BA              0.252
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
Name: 491, dtype: object
<class 'pandas.core.series.Series'>
492
Team              MIL
League             AL
Year             1996
RS                894
RA                899
W                  80
OBP             0.353
SLG             0.441
BA              0.279
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 492, dtype: object
<class 'pandas.core.series.Series'>
493
Team              MIN
League             AL
Year             1996
RS                877
RA                900
W                  78
OBP             0.357
SLG             0.425

Name: 634, dtype: object
<class 'pandas.core.series.Series'>
635
Team              STL
League             NL
Year             1989
RS                632
RA                608
W                  86
OBP             0.321
SLG             0.363
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 164
OOBP              NaN
OSLG              NaN
Name: 635, dtype: object
<class 'pandas.core.series.Series'>
636
Team              TEX
League             AL
Year             1989
RS                695
RA                714
W                  83
OBP             0.326
SLG             0.394
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 636, dtype: object
<class 'pandas.core.series.Series'>
637
Team              TOR
League             AL
Year             1989
RS                731
RA                651
W                  89
OBP             0.323
SLG             0.398
BA               0.26
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 637, dtype: object
<class 'pandas.core.series.Series'>
638
Team              ATL
League             NL
Year             1988
RS                555
RA                741
W                  54
OBP             0.298
SLG             0.348
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 638, dtype: object
<class 'pandas.core.series.Series'>
639
Team              BAL
League             AL
Year             1988
RS                550
RA                789
W                  54
OBP             0.305
SLG             0.359
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 639, dtype: object
<class 'pandas.core.series.Series'>
640
Team              BOS
League             AL
Year             1988
RS                813
RA                689
W                  89
OBP             0.357
SLG              0.42
BA              0.283
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 640, dtype: object
<class 'pandas.core.series.Series'>
641
Team              CAL
League             AL
Year             1988
RS                714
RA                771
W                  75
OBP             0.321
SLG             0.385
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 641, dtype: object
<class 'pandas.core.series.Series'>
642
Team              CHC
League             NL
Year             1988
RS                660
RA                694
W                  77
OBP              0.31
SLG             0.383
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 642, dtype: object
<class 'pandas.core.series.Series'>
643
Team              CHW
League             AL
Year             1988
RS                631
RA                757
W                  71
OBP             0.303
SLG              0.37
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 643, dtype: object
<class 'pandas.core.series.Series'>
644
Team              CIN
League             NL
Year             1988
RS                641
RA                596
W                  87
OBP             0.309
SLG             0.368
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 644, dtype: object
<class 'pandas.core.series.Series'>
645
Team              CLE
League             AL
Year             1988
RS                666
RA                731
W                  78
OBP             0.314
SLG             0.387
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 645, dtype: object
<class 'pandas.core.series.Series'>
646
Team              DET
League             AL
Year             1988
RS                703
RA                658
W                  88
OBP             0.324
SLG             0.378
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 646, dtype: object
<class 'pandas.core.series.Series'>
647
Team              HOU
League             NL
Year             1988
RS                617
RA                631
W                  82
OBP             0.306
SLG             0.351
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 647, dtype: object
<class 'pandas.core.series.Series'>
648
Team              KCR
League             AL
Year             1988
RS                704
RA                648
W                  84
OBP             0.321
SLG             0.391
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 648, dtype: object
<class 'pandas.core.series.Series'>
649
Team              LAD
League             NL
Year             1988
RS                628
RA                544
W                  94
OBP             0.305
SLG             0.352
BA              0.248
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 649, dtype: object
<class 'pandas.core.series.Series'>
650
Team              MIL
League             AL
Year             1988
RS                682
RA                616
W                  87
OBP             0.314
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 650, dtype: object
<class 'pandas.core.series.Series'>
651
Team              MIN
League             AL
Year             1988
RS                759
RA                672
W                  91
OBP              0.34
SLG             0.421
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 651, dtype: object
<class 'pandas.core.series.Series'>
652
Team              MON
League             NL
Year             1988
RS                628
RA                592
W                  81
OBP             0.309
SLG             0.373
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 652, dtype: object
<class 'pandas.core.series.Series'>
653
Team              NYM
League             NL
Year             1988
RS                703
RA                532
W                 100
OBP             0.325
SLG             0.396
BA              0.256
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 160
OOBP              NaN
OSLG              NaN
Name: 653, dtype: object
<class 'pandas.core.series.Series'>
654
Team              NYY
League             AL
Year             1988
RS                772
RA                748
W                  85
OBP             0.333
SLG             0.395
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 654, dtype: object
<class 'pandas.core.series.Series'>
655
Team              OAK
League             AL
Year             1988
RS                800
RA                620
W                 104
OBP             0.336
SLG             0.399
BA              0.263
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 655, dtype: object
<class 'pandas.core.series.Series'>
656
Team              PHI
League             NL
Year             1988
RS                597
RA                734
W                  65
OBP             0.306
SLG             0.355
BA              0.239
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 656, dtype: object
<class 'pandas.core.series.Series'>
657
Team              PIT
League             NL
Year             1988
RS                651
RA                616
W                  85
OBP             0.317
SLG             0.369
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 657, dtype: object
<class 'pandas.core.series.Series'>
658
Team              SDP
League             NL
Year             1988
RS                594
RA                583
W                  83
OBP              0.31
SLG             0.351
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 658, dtype: object
<class 'pandas.core.series.Series'>
659
Team              SEA
League             AL
Year             1988
RS                664
RA                744
W                  68
OBP             0.317
SLG             0.398
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 659, dtype: object
<class 'pandas.core.series.Series'>
660
Team              SFG
League             NL
Year             1988
RS                670
RA                626
W                  83
OBP             0.318
SLG             0.368
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 660, dtype: object
<class 'pandas.core.series.Series'>
661
Team              STL
League             NL
Year             1988
RS                578
RA                633
W                  76
OBP             0.309
SLG             0.337
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 661, dtype: object
<class 'pandas.core.series.Series'>
662
Team              TEX
League             AL
Year             1988
RS                637
RA                735
W                  70
OBP              0.32
SLG             0.368
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 662, dtype: object
<class 'pandas.core.series.Series'>
663
Team              TOR
League             AL
Year             1988
RS                763
RA                680
W                  87
OBP             0.332
SLG             0.419
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 663, dtype: object
<class 'pandas.core.series.Series'>
664
Team              ATL
League             NL
Year             1987
RS                747
RA                829
W                  69
OBP             0.339
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 664, dtype: object
<class 'pandas.core.series.Series'>
665
Team              BAL
League             AL
Year             1987
RS                729
RA                880
W                  67
OBP             0.322
SLG             0.418
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 665, dtype: object
<class 'pandas.core.series.Series'>
666
Team              BOS
League             AL
Year             1987
RS                842
RA                825
W                  78
OBP             0.352
SLG              0.43
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 666, dtype: object
<class 'pandas.core.series.Series'>
667
Team              CAL
League             AL
Year             1987
RS                770
RA                803
W                  75
OBP             0.326
SLG             0.401
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 667, dtype: object
<class 'pandas.core.series.Series'>
668
Team              CHC
League             NL
Year             1987
RS                720
RA                801
W                  76
OBP             0.326
SLG             0.432
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 668, dtype: object
<class 'pandas.core.series.Series'>
669
Team              CHW
League             AL
Year             1987
RS                748
RA                746
W                  77
OBP             0.319
SLG             0.415
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 669, dtype: object
<class 'pandas.core.series.Series'>
670
Team              CIN
League             NL
Year             1987
RS                783
RA                752
W                  84
OBP              0.33
SLG             0.427
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 670, dtype: object
<class 'pandas.core.series.Series'>
671
Team              CLE
League             AL
Year             1987
RS                742
RA                957
W                  61
OBP             0.324
SLG             0.422
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 671, dtype: object
<class 'pandas.core.series.Series'>
672
Team              DET
League             AL
Year             1987
RS                896
RA                735
W                  98
OBP             0.349
SLG             0.451
BA              0.272
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 672, dtype: object
<class 'pandas.core.series.Series'>
673
Team              HOU
League             NL
Year             1987
RS                648
RA                678
W                  76
OBP             0.318
SLG             0.373
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 673, dtype: object
<class 'pandas.core.series.Series'>
674
Team              KCR
League             AL
Year             1987
RS                715
RA                691
W                  83
OBP             0.328
SLG             0.412
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 674, dtype: object
<class 'pandas.core.series.Series'>
675
Team              LAD
League             NL
Year             1987
RS                635
RA                675
W                  73
OBP             0.309
SLG             0.371
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 675, dtype: object
<class 'pandas.core.series.Series'>
676
Team              MIL
League             AL
Year             1987
RS                862
RA                817
W                  91
OBP             0.346
SLG             0.428
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 676, dtype: object
<class 'pandas.core.series.Series'>
677
Team              MIN
League             AL
Year             1987
RS                786
RA                806
W                  85
OBP             0.328
SLG              0.43
BA              0.261
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 677, dtype: object
<class 'pandas.core.series.Series'>
678
Team              MON
League             NL
Year             1987
RS                741
RA                720
W                  91
OBP             0.328
SLG             0.401
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 678, dtype: object
<class 'pandas.core.series.Series'>
679
Team              NYM
League             NL
Year             1987
RS                823
RA                698
W                  92
OBP             0.339
SLG             0.434
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 679, dtype: object
<class 'pandas.core.series.Series'>
680
Team              NYY
League             AL
Year             1987
RS                788
RA                758
W                  89
OBP             0.336
SLG             0.418
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 680, dtype: object
<class 'pandas.core.series.Series'>
681
Team              OAK
League             AL
Year             1987
RS                806
RA                789
W                  81
OBP             0.333
SLG             0.428
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 681, dtype: object
<class 'pandas.core.series.Series'>
682
Team              PHI
League             NL
Year             1987
RS                702
RA                749
W                  80
OBP             0.327
SLG              0.41
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 682, dtype: object
<class 'pandas.core.series.Series'>
683
Team              PIT
League             NL
Year             1987
RS                723
RA                744
W                  80
OBP              0.33
SLG             0.403
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 683, dtype: object
<class 'pandas.core.series.Series'>
684
Team              SDP
League             NL
Year             1987
RS                668
RA                763
W                  65
OBP             0.332
SLG             0.378
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 684, dtype: object
<class 'pandas.core.series.Series'>
685
Team              SEA
League             AL
Year             1987
RS                760
RA                801
W                  78
OBP             0.335
SLG             0.428

Name: 868, dtype: object
<class 'pandas.core.series.Series'>
869
Team              STL
League             NL
Year             1979
RS                731
RA                693
W                  86
OBP             0.331
SLG             0.401
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 869, dtype: object
<class 'pandas.core.series.Series'>
870
Team              TEX
League             AL
Year             1979
RS                750
RA                698
W                  83
OBP             0.334
SLG             0.409
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 870, dtype: object
<class 'pandas.core.series.Series'>
871
Team              TOR
League             AL
Year             1979
RS                613
RA                862
W                  53
OBP             0.311
SLG             0.363
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 871, dtype: object
<class 'pandas.core.series.Series'>
872
Team              ATL
League             NL
Year             1978
RS                600
RA                750
W                  69
OBP             0.315
SLG             0.363
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 872, dtype: object
<class 'pandas.core.series.Series'>
873
Team              BAL
League             AL
Year             1978
RS                659
RA                633
W                  90
OBP             0.326
SLG             0.396
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 873, dtype: object
<class 'pandas.core.series.Series'>
874
Team              BOS
League             AL
Year             1978
RS                796
RA                657
W                  99
OBP             0.336
SLG             0.424
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 874, dtype: object
<class 'pandas.core.series.Series'>
875
Team              CAL
League             AL
Year             1978
RS                691
RA                666
W                  87
OBP              0.33
SLG              0.37
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 875, dtype: object
<class 'pandas.core.series.Series'>
876
Team              CHC
League             NL
Year             1978
RS                664
RA                724
W                  79
OBP             0.331
SLG             0.361
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 876, dtype: object
<class 'pandas.core.series.Series'>
877
Team              CHW
League             AL
Year             1978
RS                634
RA                731
W                  71
OBP             0.317
SLG             0.379
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 877, dtype: object
<class 'pandas.core.series.Series'>
878
Team              CIN
League             NL
Year             1978
RS                710
RA                688
W                  92
OBP             0.334
SLG             0.393
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 878, dtype: object
<class 'pandas.core.series.Series'>
879
Team              CLE
League             AL
Year             1978
RS                639
RA                694
W                  69
OBP             0.323
SLG             0.379
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 159
OOBP              NaN
OSLG              NaN
Name: 879, dtype: object
<class 'pandas.core.series.Series'>
880
Team              DET
League             AL
Year             1978
RS                714
RA                653
W                  86
OBP             0.339
SLG             0.392
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 880, dtype: object
<class 'pandas.core.series.Series'>
881
Team              HOU
League             NL
Year             1978
RS                605
RA                634
W                  74
OBP             0.313
SLG             0.355
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 881, dtype: object
<class 'pandas.core.series.Series'>
882
Team              KCR
League             AL
Year             1978
RS                743
RA                634
W                  92
OBP             0.329
SLG             0.399
BA              0.268
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 882, dtype: object
<class 'pandas.core.series.Series'>
883
Team              LAD
League             NL
Year             1978
RS                727
RA                573
W                  95
OBP             0.338
SLG             0.402
BA              0.264
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 883, dtype: object
<class 'pandas.core.series.Series'>
884
Team              MIL
League             AL
Year             1978
RS                804
RA                650
W                  93
OBP             0.339
SLG             0.432
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 884, dtype: object
<class 'pandas.core.series.Series'>
885
Team              MIN
League             AL
Year             1978
RS                666
RA                678
W                  73
OBP             0.339
SLG             0.375
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 885, dtype: object
<class 'pandas.core.series.Series'>
886
Team              MON
League             NL
Year             1978
RS                633
RA                611
W                  76
OBP             0.306
SLG             0.379
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 886, dtype: object
<class 'pandas.core.series.Series'>
887
Team              NYM
League             NL
Year             1978
RS                607
RA                690
W                  66
OBP             0.314
SLG             0.352
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 887, dtype: object
<class 'pandas.core.series.Series'>
888
Team              NYY
League             AL
Year             1978
RS                735
RA                582
W                 100
OBP             0.329
SLG             0.388
BA              0.267
Playoffs            1
RankSeason          1
RankPlayoffs        1
G                 163
OOBP              NaN
OSLG              NaN
Name: 888, dtype: object
<class 'pandas.core.series.Series'>
889
Team              OAK
League             AL
Year             1978
RS                532
RA                690
W                  69
OBP             0.303
SLG             0.351
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 889, dtype: object
<class 'pandas.core.series.Series'>
890
Team              PHI
League             NL
Year             1978
RS                708
RA                586
W                  90
OBP             0.328
SLG             0.388
BA              0.258
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 890, dtype: object
<class 'pandas.core.series.Series'>
891
Team              PIT
League             NL
Year             1978
RS                684
RA                637
W                  88
OBP              0.32
SLG             0.385
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 891, dtype: object
<class 'pandas.core.series.Series'>
892
Team              SDP
League             NL
Year             1978
RS                591
RA                598
W                  84
OBP             0.321
SLG             0.348
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 892, dtype: object
<class 'pandas.core.series.Series'>
893
Team              SEA
League             AL
Year             1978
RS                614
RA                834
W                  56
OBP             0.314
SLG             0.359
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 893, dtype: object
<class 'pandas.core.series.Series'>
894
Team              SFG
League             NL
Year             1978
RS                613
RA                594
W                  89
OBP             0.318
SLG             0.374
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 894, dtype: object
<class 'pandas.core.series.Series'>
895
Team              STL
League             NL
Year             1978
RS                600
RA                657
W                  69
OBP             0.303
SLG             0.358
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 895, dtype: object
<class 'pandas.core.series.Series'>
896
Team              TEX
League             AL
Year             1978
RS                692
RA                632
W                  87
OBP             0.332
SLG             0.381
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 896, dtype: object
<class 'pandas.core.series.Series'>
897
Team              TOR
League             AL
Year             1978
RS                590
RA                775
W                  59
OBP             0.308
SLG             0.359
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 897, dtype: object
<class 'pandas.core.series.Series'>
898
Team              ATL
League             NL
Year             1977
RS                678
RA                895
W                  61
OBP              0.32
SLG             0.376
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 898, dtype: object
<class 'pandas.core.series.Series'>
899
Team              BAL
League             AL
Year             1977
RS                719
RA                653
W                  97
OBP             0.329
SLG             0.393
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 899, dtype: object
<class 'pandas.core.series.Series'>
900
Team              BOS
League             AL
Year             1977
RS                859
RA                712
W                  97
OBP             0.345
SLG             0.465
BA              0.281
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 900, dtype: object
<class 'pandas.core.series.Series'>
901
Team              CAL
League             AL
Year             1977
RS                675
RA                695
W                  74
OBP             0.324
SLG             0.386
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 901, dtype: object
<class 'pandas.core.series.Series'>
902
Team              CHC
League             NL
Year             1977
RS                692
RA                739
W                  81
OBP              0.33
SLG             0.387
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 902, dtype: object
<class 'pandas.core.series.Series'>
903
Team              CHW
League             AL
Year             1977
RS                844
RA                771
W                  90
OBP             0.344
SLG             0.444
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 903, dtype: object
<class 'pandas.core.series.Series'>
904
Team              CIN
League             NL
Year             1977
RS                802
RA                725
W                  88
OBP             0.345
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 904, dtype: object
<class 'pandas.core.series.Series'>
905
Team              CLE
League             AL
Year             1977
RS                676
RA                739
W                  71
OBP             0.334
SLG              0.38
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 905, dtype: object
<class 'pandas.core.series.Series'>
906
Team              DET
League             AL
Year             1977
RS                714
RA                751
W                  74
OBP             0.318
SLG              0.41
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 906, dtype: object
<class 'pandas.core.series.Series'>
907
Team              HOU
League             NL
Year             1977
RS                680
RA                650
W                  81
OBP              0.32
SLG             0.385
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 907, dtype: object
<class 'pandas.core.series.Series'>
908
Team              KCR
League             AL
Year             1977
RS                822
RA                651
W                 102
OBP              0.34
SLG             0.436
BA              0.277
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 908, dtype: object
<class 'pandas.core.series.Series'>
909
Team              LAD
League             NL
Year             1977
RS                769
RA                582
W                  98
OBP             0.336
SLG             0.418
BA              0.266
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 909, dtype: object
<class 'pandas.core.series.Series'>
910
Team              MIL
League             AL
Year             1977
RS                639
RA                765
W                  67
OBP             0.314
SLG             0.389
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 910, dtype: object
<class 'pandas.core.series.Series'>
911
Team              MIN
League             AL
Year             1977
RS                867
RA                776
W                  84
OBP             0.348
SLG             0.417
BA              0.282
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 911, dtype: object
<class 'pandas.core.series.Series'>
912
Team              MON
League             NL
Year             1977
RS                665
RA                736
W                  75
OBP             0.318
SLG             0.402
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 912, dtype: object
<class 'pandas.core.series.Series'>
913
Team              NYM
League             NL
Year             1977
RS                587
RA                663
W                  64
OBP             0.313
SLG             0.346
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 913, dtype: object
<class 'pandas.core.series.Series'>
914
Team              NYY
League             AL
Year             1977
RS                831
RA                651
W                 100
OBP             0.344
SLG             0.444
BA              0.281
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 914, dtype: object
<class 'pandas.core.series.Series'>
915
Team              OAK
League             AL
Year             1977
RS                605
RA                749
W                  63
OBP             0.308
SLG             0.352
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 915, dtype: object
<class 'pandas.core.series.Series'>
916
Team              PHI
League             NL
Year             1977
RS                847
RA                668
W                 101
OBP             0.346
SLG             0.448
BA              0.279
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 916, dtype: object
<class 'pandas.core.series.Series'>
917
Team              PIT
League             NL
Year             1977
RS                734
RA                665
W                  96
OBP             0.331
SLG             0.413
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 917, dtype: object
<class 'pandas.core.series.Series'>
918
Team              SDP
League             NL
Year             1977
RS                692
RA                834
W                  69
OBP             0.324
SLG             0.375
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 918, dtype: object
<class 'pandas.core.series.Series'>
919
Team              SEA
League             AL
Year             1977
RS                624
RA                855
W                  64
OBP             0.312
SLG             0.381

Team              KCR
League             AL
Year             1973
RS                755
RA                752
W                  88
OBP             0.339
SLG             0.381
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1006, dtype: object
<class 'pandas.core.series.Series'>
1007
Team              LAD
League             NL
Year             1973
RS                675
RA                565
W                  95
OBP             0.323
SLG             0.371
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1007, dtype: object
<class 'pandas.core.series.Series'>
1008
Team              MIL
League             AL
Year             1973
RS                708
RA                731
W                  74
OBP             0.325
SLG             0.388
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1008, dtype: object
<class 'pandas.core.series.Series'>
1009
Team              MIN
League             AL
Year             1973
RS                738
RA                692
W                  81
OBP             0.342
SLG             0.393
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1009, dtype: object
<class 'pandas.core.series.Series'>
1010
Team              MON
League             NL
Year             1973
RS                668
RA                702
W                  79
OBP              0.34
SLG             0.364
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1010, dtype: object
<class 'pandas.core.series.Series'>
1011
Team              NYM
League             NL
Year             1973
RS                608
RA                588
W                  82
OBP             0.315
SLG             0.338
BA              0.246
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 161
OOBP              NaN
OSLG              NaN
Name: 1011, dtype: object
<class 'pandas.core.series.Series'>
1012
Team              NYY
League             AL
Year             1973
RS                641
RA                610
W                  80
OBP             0.322
SLG             0.378
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1012, dtype: object
<class 'pandas.core.series.Series'>
1013
Team              OAK
League             AL
Year             1973
RS                758
RA                615
W                  94
OBP             0.333
SLG             0.389
BA               0.26
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1013, dtype: object
<class 'pandas.core.series.Series'>
1014
Team              PHI
League             NL
Year             1973
RS                642
RA                717
W                  71
OBP              0.31
SLG             0.371
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1014, dtype: object
<class 'pandas.core.series.Series'>
1015
Team              PIT
League             NL
Year             1973
RS                704
RA                693
W                  80
OBP             0.315
SLG             0.405
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1015, dtype: object
<class 'pandas.core.series.Series'>
1016
Team              SDP
League             NL
Year             1973
RS                548
RA                770
W                  60
OBP             0.296
SLG             0.351
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1016, dtype: object
<class 'pandas.core.series.Series'>
1017
Team              SFG
League             NL
Year             1973
RS                739
RA                702
W                  88
OBP             0.335
SLG             0.407
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1017, dtype: object
<class 'pandas.core.series.Series'>
1018
Team              STL
League             NL
Year             1973
RS                643
RA                603
W                  81
OBP             0.325
SLG             0.357
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1018, dtype: object
<class 'pandas.core.series.Series'>
1019
Team              TEX
League             AL
Year             1973
RS                619
RA                844
W                  57
OBP             0.318
SLG             0.361
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1019, dtype: object
<class 'pandas.core.series.Series'>
1020
Team              ATL
League             NL
Year             1971
RS                643
RA                699
W                  82
OBP             0.312
SLG             0.385
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1020, dtype: object
<class 'pandas.core.series.Series'>
1021
Team              BAL
League             AL
Year             1971
RS                742
RA                530
W                 101
OBP             0.347
SLG             0.398
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 158
OOBP              NaN
OSLG              NaN
Name: 1021, dtype: object
<class 'pandas.core.series.Series'>
1022
Team              BOS
League             AL
Year             1971
RS                691
RA                667
W                  85
OBP             0.322
SLG             0.397
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1022, dtype: object
<class 'pandas.core.series.Series'>
1023
Team              CAL
League             AL
Year             1971
RS                511
RA                576
W                  76
OBP              0.29
SLG             0.329
BA              0.231
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1023, dtype: object
<class 'pandas.core.series.Series'>
1024
Team              CHC
League             NL
Year             1971
RS                637
RA                648
W                  83
OBP             0.325
SLG             0.378
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1024, dtype: object
<class 'pandas.core.series.Series'>
1025
Team              CHW
League             AL
Year             1971
RS                617
RA                597
W                  79
OBP             0.325
SLG             0.373
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1025, dtype: object
<class 'pandas.core.series.Series'>
1026
Team              CIN
League             NL
Year             1971
RS                586
RA                581
W                  79
OBP               0.3
SLG             0.366
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1026, dtype: object
<class 'pandas.core.series.Series'>
1027
Team              CLE
League             AL
Year             1971
RS                543
RA                747
W                  60
OBP               0.3
SLG             0.342
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1027, dtype: object
<class 'pandas.core.series.Series'>
1028
Team              DET
League             AL
Year             1971
RS                701
RA                645
W                  91
OBP             0.325
SLG             0.405
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1028, dtype: object
<class 'pandas.core.series.Series'>
1029
Team              HOU
League             NL
Year             1971
RS                585
RA                567
W                  79
OBP             0.302
SLG              0.34
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1029, dtype: object
<class 'pandas.core.series.Series'>
1030
Team              KCR
League             AL
Year             1971
RS                603
RA                566
W                  85
OBP             0.313
SLG             0.353
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1030, dtype: object
<class 'pandas.core.series.Series'>
1031
Team              LAD
League             NL
Year             1971
RS                663
RA                587
W                  89
OBP             0.325
SLG              0.37
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1031, dtype: object
<class 'pandas.core.series.Series'>
1032
Team              MIL
League             AL
Year             1971
RS                534
RA                609
W                  69
OBP             0.304
SLG             0.329
BA              0.229
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1032, dtype: object
<class 'pandas.core.series.Series'>
1033
Team              MIN
League             AL
Year             1971
RS                654
RA                670
W                  74
OBP             0.323
SLG             0.372
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 1033, dtype: object
<class 'pandas.core.series.Series'>
1034
Team              MON
League             NL
Year             1971
RS                622
RA                729
W                  71
OBP             0.322
SLG             0.343
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1034, dtype: object
<class 'pandas.core.series.Series'>
1035
Team              NYM
League             NL
Year             1971
RS                588
RA                550
W                  83
OBP             0.319
SLG             0.351
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1035, dtype: object
<class 'pandas.core.series.Series'>
1036
Team              NYY
League             AL
Year             1971
RS                648
RA                641
W                  81
OBP             0.328
SLG              0.36
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1036, dtype: object
<class 'pandas.core.series.Series'>
1037
Team              OAK
League             AL
Year             1971
RS                691
RA                564
W                 101
OBP             0.321
SLG             0.384
BA              0.252
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 161
OOBP              NaN
OSLG              NaN
Name: 1037, dtype: object
<class 'pandas.core.series.Series'>
1038
Team              PHI
League             NL
Year             1971
RS                558
RA                688
W                  67
OBP             0.298
SLG              0.35
BA              0.233
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1038, dtype: object
<class 'pandas.core.series.Series'>
1039
Team              PIT
League             NL
Year             1971
RS                788
RA                599
W                  97
OBP              0.33
SLG             0.416
BA              0.274
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1039, dtype: object
<class 'pandas.core.series.Series'>
1040
Team              SDP
League             NL
Year             1971
RS                486
RA                610
W                  61
OBP             0.293
SLG             0.332
BA              0.233
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1040, dtype: object
<class 'pandas.core.series.Series'>
1041
Team              SFG
League             NL
Year             1971
RS                706
RA                644
W                  90
OBP             0.329
SLG             0.378
BA              0.247
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 1041, dtype: object
<class 'pandas.core.series.Series'>
1042
Team              STL
League             NL
Year             1971
RS                739
RA                699
W                  90
OBP             0.338
SLG             0.385
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 1042, dtype: object
<class 'pandas.core.series.Series'>
1043
Team              WSA
League             AL
Year             1971
RS                537
RA                660
W                  63
OBP             0.307
SLG             0.326
BA               0.23
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 159
OOBP              NaN
OSLG              NaN
Name: 1043, dtype: object
<class 'pandas.core.series.Series'>
1044
Team              ATL
League             NL
Year             1970
RS                736
RA                772
W                  76
OBP             0.334
SLG             0.404
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1044, dtype: object
<class 'pandas.core.series.Series'>
1045
Team              BAL
League             AL
Year             1970
RS                792
RA                574
W                 108
OBP             0.344
SLG             0.401
BA              0.257
Playoffs            1
RankSeason          1
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1045, dtype: object
<class 'pandas.core.series.Series'>
1046
Team              BOS
League             AL
Year             1970
RS                786
RA                722
W                  87
OBP             0.335
SLG             0.428
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1046, dtype: object
<class 'pandas.core.series.Series'>
1047
Team              CAL
League             AL
Year             1970
RS                631
RA                630
W                  86
OBP             0.309
SLG             0.363
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1047, dtype: object
<class 'pandas.core.series.Series'>
1048
Team              CHC
League             NL
Year             1970
RS                806
RA                679
W                  84
OBP             0.333
SLG             0.415
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1048, dtype: object
<class 'pandas.core.series.Series'>
1049
Team              CHW
League             AL
Year             1970
RS                633
RA                822
W                  56
OBP             0.315
SLG             0.362
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1049, dtype: object
<class 'pandas.core.series.Series'>
1050
Team              CIN
League             NL
Year             1970
RS                775
RA                681
W                 102
OBP             0.336
SLG             0.436
BA               0.27
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 1050, dtype: object
<class 'pandas.core.series.Series'>
1051
Team              CLE
League             AL
Year             1970
RS                649
RA                675
W                  76
OBP             0.314
SLG             0.394
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1051, dtype: object
<class 'pandas.core.series.Series'>
1052
Team              DET
League             AL
Year             1970
RS                666
RA                731
W                  79
OBP             0.322
SLG             0.374
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1052, dtype: object
<class 'pandas.core.series.Series'>
1053
Team              HOU
League             NL
Year             1970
RS                744
RA                763
W                  79
OBP             0.332
SLG             0.391
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1053, dtype: object
<class 'pandas.core.series.Series'>
1054
Team              KCR
League             AL
Year             1970
RS                611
RA                705
W                  65
OBP             0.309
SLG             0.348
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1054, dtype: object
<class 'pandas.core.series.Series'>
1055
Team              LAD
League             NL
Year             1970
RS                749
RA                684
W                  87
OBP             0.334
SLG             0.382
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1055, dtype: object
<class 'pandas.core.series.Series'>
1056
Team              MIL
League             AL
Year             1970
RS                613
RA                751
W                  65

Team              PHI
League             NL
Year             1963
RS                642
RA                578
W                  87
OBP             0.306
SLG             0.381
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1207, dtype: object
<class 'pandas.core.series.Series'>
1208
Team              PIT
League             NL
Year             1963
RS                567
RA                595
W                  74
OBP             0.309
SLG             0.359
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1208, dtype: object
<class 'pandas.core.series.Series'>
1209
Team              SFG
League             NL
Year             1963
RS                725
RA                641
W                  88
OBP             0.316
SLG             0.414
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1209, dtype: object
<class 'pandas.core.series.Series'>
1210
Team              STL
League             NL
Year             1963
RS                747
RA                628
W                  93
OBP             0.326
SLG             0.403
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1210, dtype: object
<class 'pandas.core.series.Series'>
1211
Team              WSA
League             AL
Year             1963
RS                578
RA                812
W                  56
OBP             0.293
SLG             0.351
BA              0.227
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1211, dtype: object
<class 'pandas.core.series.Series'>
1212
Team              BAL
League             AL
Year             1962
RS                652
RA                680
W                  77
OBP             0.314
SLG             0.387
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1212, dtype: object
<class 'pandas.core.series.Series'>
1213
Team              BOS
League             AL
Year             1962
RS                707
RA                756
W                  76
OBP             0.324
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 1213, dtype: object
<class 'pandas.core.series.Series'>
1214
Team              CHC
League             NL
Year             1962
RS                632
RA                827
W                  59
OBP             0.317
SLG             0.377
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1214, dtype: object
<class 'pandas.core.series.Series'>
1215
Team              CHW
League             AL
Year             1962
RS                707
RA                658
W                  85
OBP             0.334
SLG             0.372
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1215, dtype: object
<class 'pandas.core.series.Series'>
1216
Team              CIN
League             NL
Year             1962
RS                802
RA                685
W                  98
OBP             0.332
SLG             0.417
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1216, dtype: object
<class 'pandas.core.series.Series'>
1217
Team              CLE
League             AL
Year             1962
RS                682
RA                745
W                  80
OBP             0.312
SLG             0.388
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1217, dtype: object
<class 'pandas.core.series.Series'>
1218
Team              DET
League             AL
Year             1962
RS                758
RA                692
W                  85
OBP              0.33
SLG             0.411
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1218, dtype: object
<class 'pandas.core.series.Series'>
1219
Team              HOU
League             NL
Year             1962
RS                592
RA                717
W                  64
OBP              0.31
SLG             0.351
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1219, dtype: object
<class 'pandas.core.series.Series'>
1220
Team              KCA
League             AL
Year             1962
RS                745
RA                837
W                  72
OBP             0.332
SLG             0.386
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1220, dtype: object
<class 'pandas.core.series.Series'>
1221
Team              LAA
League             AL
Year             1962
RS                718
RA                706
W                  86
OBP             0.325
SLG              0.38
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1221, dtype: object
<class 'pandas.core.series.Series'>
1222
Team              LAD
League             NL
Year             1962
RS                842
RA                697
W                 102
OBP             0.337
SLG               0.4
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 165
OOBP              NaN
OSLG              NaN
Name: 1222, dtype: object
<class 'pandas.core.series.Series'>
1223
Team              MIN
League             AL
Year             1962
RS                798
RA                713
W                  91
OBP             0.338
SLG             0.412
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 1223, dtype: object
<class 'pandas.core.series.Series'>
1224
Team              MLN
League             NL
Year             1962
RS                730
RA                665
W                  86
OBP             0.326
SLG             0.403
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1224, dtype: object
<class 'pandas.core.series.Series'>
1225
Team              NYM
League             NL
Year             1962
RS                617
RA                948
W                  40
OBP             0.318
SLG             0.361
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1225, dtype: object
<class 'pandas.core.series.Series'>
1226
Team              NYY
League             AL
Year             1962
RS                817
RA                680
W                  96
OBP             0.337
SLG             0.426
BA              0.267
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1226, dtype: object
<class 'pandas.core.series.Series'>
1227
Team             PHI
League            NL
Year            1962
RS               705
RA               759
W                 81
OBP             0.33
SLG             0.39
BA              0.26
Playoffs           0
RankSeason       NaN
RankPlayoffs     NaN
G                161
OOBP             NaN
OSLG             NaN
Name: 1227, dtype: object
<class 'pandas.core.series.Series'>
1228
Team              PIT
League             NL
Year             1962
RS                706
RA                626
W                  93
OBP             0.321
SLG             0.394
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1228, dtype: object
<class 'pandas.core.series.Series'>
1229
Team              SFG
League             NL
Year             1962
RS                878
RA                690
W                 103
OBP             0.341
SLG             0.441
BA              0.278
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 165
OOBP              NaN
OSLG              NaN
Name: 1229, dtype: object
<class 'pandas.core.series.Series'>
1230
Team              STL
League             NL
Year             1962
RS                774
RA                664
W                  84
OBP             0.335
SLG             0.394
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 1230, dtype: object
<class 'pandas.core.series.Series'>
1231
Team              WSA
League             AL
Year             1962
RS                599
RA                716
W                  60
OBP             0.308
SLG             0.373
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1231, dtype: object
<class 'pandas.core.series.Series'>

In [49]:
# Print the row and type of each row
for row_tuple in pit_df.iterrows():
    print(row_tuple)
    print(type(row_tuple))

(0, Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
Name: 0, dtype: object)
<class 'tuple'>
(1, Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
Name: 1, dtype: object)
<class 'tuple'>
(2, Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
Name: 2, dtype: object)
<class 'tuple'>
(3, Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
Name: 3, dtype: object)
<class 'tuple'>
(4, Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
Name: 4, dtype: object)
<class 'tuple'>
(5, Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
Name: 5, dtype: object)
<class 'tuple'>
(6, Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
Name: 6, dtype: object)
<class 'tuple'>
(7, Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
Name: 7, dtype: object)
<class 'tuple'>
(8, Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
Name: 8, dtype: object)
<class 'tuple'>
(9, Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
Name: 9, dtype: object)
<class 'tuple'>
(10, Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
Name: 10, dtype: object)
<class 'tuple'>
(11, Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
Name: 11, dtype: object)
<class 'tuple'>
(12, Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
Name: 12, dtype: object)
<class 'tuple'>
(13, Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
Name: 13, dtype: object)
<class 'tuple'>
(14, Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
Name: 14, dtype: object)
<class 'tuple'>
(15, Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
Name: 15, dtype: object)
<class 'tuple'>
(16, Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
Name: 16, dtype: object)
<class 'tuple'>
(17, Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
Name: 17, dtype: object)
<class 'tuple'>
(18, Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
Name: 18, dtype: object)
<class 'tuple'>
(19, Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
Name: 19, dtype: object)
<class 'tuple'>
(20, Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
Name: 20, dtype: object)
<class 'tuple'>
(21, Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
Name: 21, dtype: object)
<class 'tuple'>
(22, Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
Name: 22, dtype: object)
<class 'tuple'>
(23, Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
Name: 23, dtype: object)
<class 'tuple'>
(24, Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
Name: 24, dtype: object)
<class 'tuple'>
(25, Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
Name: 25, dtype: object)
<class 'tuple'>
(26, Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
Name: 26, dtype: object)
<class 'tuple'>
(27, Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
Name: 27, dtype: object)
<class 'tuple'>
(28, Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
Name: 28, dtype: object)
<class 'tuple'>
(29, Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
Name: 29, dtype: object)
<class 'tuple'>
(30, Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
Name: 30, dtype: object)
<class 'tuple'>
(31, Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
Name: 31, dtype: object)
<class 'tuple'>
(32, Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
Name: 32, dtype: object)
<class 'tuple'>
(33, Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
Name: 33, dtype: object)
<class 'tuple'>
(34, Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
Name: 34, dtype: object)
<class 'tuple'>
(35, Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
Name: 35, dtype: object)
<class 'tuple'>
(36, Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
Name: 36, dtype: object)
<class 'tuple'>
(37, Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
Name: 37, dtype: object)
<class 'tuple'>
(38, Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
Name: 38, dtype: object)
<class 'tuple'>
(39, Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
Name: 39, dtype: object)
<class 'tuple'>
(40, Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
Name: 40, dtype: object)
<class 'tuple'>
(41, Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
Name: 41, dtype: object)
<class 'tuple'>
(42, Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
Name: 42, dtype: object)
<class 'tuple'>
(43, Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
Name: 43, dtype: object)
<class 'tuple'>
(44, Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
Name: 44, dtype: object)
<class 'tuple'>
(45, Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.304
OSLG            0.385
Name: 45, dtype: object)
<class 'tuple'>
(46, Team              MIN
League             AL
Year             2011
RS                619
RA                804
W                  63
OBP             0.306
SLG              0.36
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.435
Name: 46, dtype: object)
<class 'tuple'>
(47, Team              NYM
League             NL
Year             2011
RS                718
RA                742
W                  77
OBP             0.335
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.411
Name: 47, dtype: object)
<class 'tuple'>
(48, Team              NYY
League             AL
Year             2011
RS                867
RA                657
W                  97
OBP             0.343
SLG             0.444
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
Name: 48, dtype: object)
<class 'tuple'>
(49, Team              OAK
League             AL
Year             2011
RS                645
RA                679
W                  74
OBP             0.311
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.378
Name: 49, dtype: object)
<class 'tuple'>
(50, Team              PHI
League             NL
Year             2011
RS                713
RA                529
W                 102
OBP             0.323
SLG             0.395
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.296
OSLG            0.361
Name: 50, dtype: object)
<class 'tuple'>
(51, Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
Name: 51, dtype: object)
<class 'tuple'>
(52, Team              SDP
League             NL
Year             2011
RS                593
RA                611
W                  71
OBP             0.305
SLG             0.349
BA              0.237
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG            0.375
Name: 52, dtype: object)
<class 'tuple'>
(53, Team              SEA
League             AL
Year             2011

Name: 279, dtype: object)
<class 'tuple'>
(280, Team              DET
League             AL
Year             2003
RS                591
RA                928
W                  43
OBP               0.3
SLG             0.375
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.461
Name: 280, dtype: object)
<class 'tuple'>
(281, Team              FLA
League             NL
Year             2003
RS                751
RA                692
W                  91
OBP             0.333
SLG             0.421
BA              0.266
Playoffs            1
RankSeason          5
RankPlayoffs        1
G                 162
OOBP            0.325
OSLG            0.396
Name: 281, dtype: object)
<class 'tuple'>
(282, Team              HOU
League             NL
Year             2003
RS                805
RA                677
W                  87
OBP             0.336
SLG             0.431
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.397
Name: 282, dtype: object)
<class 'tuple'>
(283, Team              KCR
League             AL
Year             2003
RS                836
RA                867
W                  83
OBP             0.336
SLG             0.427
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG             0.45
Name: 283, dtype: object)
<class 'tuple'>
(284, Team              LAD
League             NL
Year             2003
RS                574
RA                556
W                  85
OBP             0.303
SLG             0.368
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.354
Name: 284, dtype: object)
<class 'tuple'>
(285, Team              MIL
League             NL
Year             2003
RS                714
RA                873
W                  68
OBP             0.329
SLG             0.419
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.462
Name: 285, dtype: object)
<class 'tuple'>
(286, Team              MIN
League             AL
Year             2003
RS                801
RA                758
W                  90
OBP             0.341
SLG             0.431
BA              0.277
Playoffs            1
RankSeason          6
RankPlayoffs        4
G                 162
OOBP            0.319
OSLG            0.428
Name: 286, dtype: object)
<class 'tuple'>
(287, Team              MON
League             NL
Year             2003
RS                711
RA                716
W                  83
OBP             0.326
SLG             0.401
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.423
Name: 287, dtype: object)
<class 'tuple'>
(288, Team              NYM
League             NL
Year             2003
RS                642
RA                754
W                  66
OBP             0.314
SLG             0.374
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.345
OSLG            0.438
Name: 288, dtype: object)
<class 'tuple'>
(289, Team              NYY
League             AL
Year             2003
RS                877
RA                716
W                 101
OBP             0.356
SLG             0.453
BA              0.271
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 163
OOBP            0.314
OSLG            0.407
Name: 289, dtype: object)
<class 'tuple'>
(290, Team              OAK
League             AL
Year             2003
RS                768
RA                643
W                  96
OBP             0.327
SLG             0.417
BA              0.254
Playoffs            1
RankSeason          3
RankPlayoffs        4
G                 162
OOBP            0.314
OSLG            0.376
Name: 290, dtype: object)
<class 'tuple'>
(291, Team              PHI
League             NL
Year             2003
RS                791
RA                697
W                  86
OBP             0.343
SLG             0.419
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.401
Name: 291, dtype: object)
<class 'tuple'>
(292, Team              PIT
League             NL
Year             2003
RS                753
RA                801
W                  75
OBP             0.338
SLG              0.42
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.431
Name: 292, dtype: object)
<class 'tuple'>
(293, Team              SDP
League             NL
Year             2003
RS                678
RA                831
W                  64
OBP             0.333
SLG             0.388
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG            0.437
Name: 293, dtype: object)
<class 'tuple'>
(294, Team              SEA
League             AL
Year             2003
RS                795
RA                637
W                  93
OBP             0.344
SLG              0.41
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.311
OSLG            0.388
Name: 294, dtype: object)
<class 'tuple'>
(295, Team              SFG
League             NL
Year             2003
RS                755
RA                638
W                 100
OBP             0.338
SLG             0.425
BA              0.264
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 161
OOBP            0.321
OSLG            0.386
Name: 295, dtype: object)
<class 'tuple'>
(296, Team              STL
League             NL
Year             2003
RS                876
RA                796
W                  85
OBP              0.35
SLG             0.454
BA              0.279
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.452
Name: 296, dtype: object)
<class 'tuple'>
(297, Team              TBD
League             AL
Year             2003
RS                715
RA                852
W                  63
OBP              0.32
SLG             0.404
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.347
OSLG             0.44
Name: 297, dtype: object)
<class 'tuple'>
(298, Team              TEX
League             AL
Year             2003
RS                826
RA                969
W                  71
OBP              0.33
SLG             0.454
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.36
OSLG            0.473
Name: 298, dtype: object)
<class 'tuple'>
(299, Team              TOR
League             AL
Year             2003
RS                894
RA                826
W                  86
OBP             0.349
SLG             0.455
BA              0.279
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.441
Name: 299, dtype: object)
<class 'tuple'>
(300, Team              ANA
League             AL
Year             2002
RS                851
RA                644
W                  99
OBP             0.341
SLG             0.433
BA              0.282
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP            0.314
OSLG            0.392
Name: 300, dtype: object)
<class 'tuple'>
(301, Team              ARI
League             NL
Year             2002
RS                819
RA                674
W                  98
OBP             0.346
SLG             0.423
BA              0.267
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG            0.397
Name: 301, dtype: object)
<class 'tuple'>
(302, Team              ATL
League             NL
Year             2002
RS                708
RA                565
W                 101
OBP             0.331
SLG             0.409
BA               0.26
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 161
OOBP            0.313
OSLG            0.364
Name: 302, dtype: object)
<class 'tuple'>
(303, Team              BAL
League             AL
Year             2002
RS                667
RA                773
W                  67
OBP             0.309
SLG             0.403
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.435
Name: 303, dtype: object)
<class 'tuple'>
(304, Team              BOS
League             AL
Year             2002
RS                859
RA                665
W                  93
OBP             0.345
SLG             0.444
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.385
Name: 304, dtype: object)
<class 'tuple'>
(305, Team              CHC
League             NL
Year             2002
RS                706
RA                759
W                  67
OBP             0.321
SLG             0.413
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.407
Name: 305, dtype: object)
<class 'tuple'>
(306, Team              CHW
League             AL
Year             2002
RS                856
RA                798
W                  81
OBP             0.338
SLG             0.449
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.33
OSLG            0.423
Name: 306, dtype: object)
<class 'tuple'>
(307, Team              CIN
League             NL
Year             2002
RS                709
RA                774
W                  78
OBP              0.33
SLG             0.408
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.426
Name: 307, dtype: object)
<class 'tuple'>
(308, Team              CLE
League             AL
Year             2002
RS                739
RA                837
W                  74
OBP             0.321
SLG             0.412
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG            0.423
Name: 308, dtype: object)
<class 'tuple'>
(309, Team              COL
League             NL
Year             2002
RS                778
RA                898
W                  73
OBP             0.337
SLG             0.423
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.349
OSLG            0.466
Name: 309, dtype: object)
<class 'tuple'>
(310, Team              DET
League             AL
Year             2002
RS                575
RA                864
W                  55
OBP               0.3
SLG             0.379
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.343
OSLG            0.455
Name: 310, dtype: object)
<class 'tuple'>
(311, Team              FLA
League             NL
Year             2002
RS                699
RA                763
W                  79
OBP             0.337
SLG             0.403
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG            0.415
Name: 311, dtype: object)
<class 'tuple'>
(312, Team              HOU
League             NL
Year             2002
RS                749
RA                695
W                  84
OBP             0.338
SLG             0.417
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.33
OSLG             0.41
Name: 312, dtype: object)
<class 'tuple'>
(313, Team              KCR
League             AL
Year             2002
RS                737
RA                891
W                  62
OBP             0.323
SLG             0.398
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.349
OSLG            0.464
Name: 313, dtype: object)
<class 'tuple'>
(314, Team              LAD
League             NL
Year             2002
RS                713
RA                643
W                  92
OBP              0.32
SLG             0.409
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.387
Name: 314, dtype: object)
<class 'tuple'>
(315, Team              MIL
League             NL
Year             2002
RS                627
RA                821
W                  56
OBP              0.32
SLG              0.39
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.442
Name: 315, dtype: object)
<class 'tuple'>
(316, Team              MIN
League             AL
Year             2002
RS                768
RA                712
W                  94
OBP             0.332
SLG             0.437
BA              0.272
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 161
OOBP            0.318
OSLG            0.421
Name: 316, dtype: object)
<class 'tuple'>
(317, Team              MON
League             NL
Year             2002
RS                735
RA                718
W                  83
OBP             0.334
SLG             0.418
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.421
Name: 317, dtype: object)
<class 'tuple'>
(318, Team              NYM
League             NL
Year             2002
RS                690
RA                703
W                  75
OBP             0.322
SLG             0.395
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.327
OSLG            0.403
Name: 318, dtype: object)
<class 'tuple'>
(319, Team              NYY
League             AL
Year             2002
RS                897
RA                697
W                 103
OBP             0.354
SLG             0.455
BA              0.275
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 161
OOBP            0.309
OSLG            0.395
Name: 319, dtype: object)
<class 'tuple'>
(320, Team              OAK
League             AL
Year             2002
RS                800
RA                654
W                 103
OBP             0.339
SLG             0.432
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.384
Name: 320, dtype: object)
<class 'tuple'>
(321, Team              PHI
League             NL
Year             2002
RS                710
RA                724
W                  80
OBP             0.339
SLG             0.422
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.328
OSLG            0.401
Name: 321, dtype: object)
<class 'tuple'>
(322, Team              PIT
League             NL
Year             2002
RS                641
RA                730
W                  72
OBP             0.319
SLG             0.381
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.342
OSLG            0.423
Name: 322, dtype: object)
<class 'tuple'>
(323, Team              SDP
League             NL
Year             2002
RS                662
RA                815
W                  66
OBP             0.321
SLG             0.381
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.346
OSLG            0.442
Name: 323, dtype: object)
<class 'tuple'>
(324, Team              SEA
League             AL
Year             2002
RS                814
RA                699
W                  93
OBP              0.35
SLG             0.419
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG             0.41
Name: 324, dtype: object)
<class 'tuple'>
(325, Team              SFG
League             NL
Year             2002
RS                783
RA                616
W                  95
OBP             0.344
SLG             0.442
BA              0.267
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.319
OSLG            0.372
Name: 325, dtype: object)
<class 'tuple'>
(326, Team              STL
League             NL
Year             2002
RS                787
RA                648
W                  97
OBP             0.338
SLG             0.425
BA              0.268
Playoffs            1
RankSeason          5
RankPlayoffs        3
G                 162
OOBP            0.323
OSLG            0.386
Name: 326, dtype: object)
<class 'tuple'>
(327, Team              TBD
League             AL
Year             2002
RS                673
RA                918
W                  55
OBP             0.314
SLG              0.39
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.357
OSLG            0.463
Name: 327, dtype: object)
<class 'tuple'>
(328, Team              TEX
League             AL
Year             2002
RS                843
RA                882
W                  72
OBP             0.338
SLG             0.455
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.355
OSLG            0.451
Name: 328, dtype: object)
<class 'tuple'>
(329, Team              TOR
League             AL
Year             2002
RS                813
RA                828
W                  78
OBP             0.327
SLG              0.43
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.344
OSLG            0.431
Name: 329, dtype: object)
<class 'tuple'>
(330, Team              ANA
League             AL
Year             2001
RS                691
RA                730
W                  75
OBP             0.327
SLG             0.405
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.412
Name: 330, dtype: object)
<class 'tuple'>
(331, Team              ARI
League             NL
Year             2001
RS                818
RA                677
W                  92
OBP             0.341
SLG             0.442
BA              0.267
Playoffs            1
RankSeason          5
RankPlayoffs        1
G                 162
OOBP            0.311
OSLG            0.404
Name: 331, dtype: object)
<class 'tuple'>
(332, Team              ATL
League             NL
Year             2001
RS                729
RA                643
W                  88
OBP             0.324
SLG             0.412
BA               0.26
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 162

(534, Team              ATL
League             NL
Year             1992
RS                682
RA                569
W                  98
OBP             0.316
SLG             0.388
BA              0.254
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 534, dtype: object)
<class 'tuple'>
(535, Team              BAL
League             AL
Year             1992
RS                705
RA                656
W                  89
OBP              0.34
SLG             0.398
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 535, dtype: object)
<class 'tuple'>
(536, Team              BOS
League             AL
Year             1992
RS                599
RA                669
W                  73
OBP             0.321
SLG             0.347
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 536, dtype: object)
<class 'tuple'>
(537, Team              CAL
League             AL
Year             1992
RS                579
RA                671
W                  72
OBP             0.301
SLG             0.338
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 537, dtype: object)
<class 'tuple'>
(538, Team              CHC
League             NL
Year             1992
RS                593
RA                624
W                  78
OBP             0.307
SLG             0.364
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 538, dtype: object)
<class 'tuple'>
(539, Team              CHW
League             AL
Year             1992
RS                738
RA                690
W                  86
OBP             0.336
SLG             0.383
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 539, dtype: object)
<class 'tuple'>
(540, Team              CIN
League             NL
Year             1992
RS                660
RA                609
W                  90
OBP             0.328
SLG             0.382
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 540, dtype: object)
<class 'tuple'>
(541, Team              CLE
League             AL
Year             1992
RS                674
RA                746
W                  76
OBP             0.323
SLG             0.383
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 541, dtype: object)
<class 'tuple'>
(542, Team              DET
League             AL
Year             1992
RS                791
RA                794
W                  75
OBP             0.337
SLG             0.407
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 542, dtype: object)
<class 'tuple'>
(543, Team              HOU
League             NL
Year             1992
RS                608
RA                668
W                  81
OBP             0.313
SLG             0.359
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 543, dtype: object)
<class 'tuple'>
(544, Team              KCR
League             AL
Year             1992
RS                610
RA                667
W                  72
OBP             0.315
SLG             0.364
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 544, dtype: object)
<class 'tuple'>
(545, Team              LAD
League             NL
Year             1992
RS                548
RA                636
W                  63
OBP             0.313
SLG             0.339
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 545, dtype: object)
<class 'tuple'>
(546, Team              MIL
League             AL
Year             1992
RS                740
RA                604
W                  92
OBP              0.33
SLG             0.375
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 546, dtype: object)
<class 'tuple'>
(547, Team              MIN
League             AL
Year             1992
RS                747
RA                653
W                  90
OBP             0.341
SLG             0.391
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 547, dtype: object)
<class 'tuple'>
(548, Team              MON
League             NL
Year             1992
RS                648
RA                581
W                  87
OBP             0.313
SLG              0.37
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 548, dtype: object)
<class 'tuple'>
(549, Team              NYM
League             NL
Year             1992
RS                599
RA                653
W                  72
OBP              0.31
SLG             0.342
BA              0.235
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 549, dtype: object)
<class 'tuple'>
(550, Team              NYY
League             AL
Year             1992
RS                733
RA                746
W                  76
OBP             0.328
SLG             0.406
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 550, dtype: object)
<class 'tuple'>
(551, Team              OAK
League             AL
Year             1992
RS                745
RA                672
W                  96
OBP             0.346
SLG             0.386
BA              0.258
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 551, dtype: object)
<class 'tuple'>
(552, Team              PHI
League             NL
Year             1992
RS                686
RA                717
W                  70
OBP              0.32
SLG             0.377
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 552, dtype: object)
<class 'tuple'>
(553, Team              PIT
League             NL
Year             1992
RS                693
RA                595
W                  96
OBP             0.324
SLG             0.381
BA              0.255
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 553, dtype: object)
<class 'tuple'>
(554, Team              SDP
League             NL
Year             1992
RS                617
RA                636
W                  82
OBP             0.313
SLG             0.386
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 554, dtype: object)
<class 'tuple'>
(555, Team              SEA
League             AL
Year             1992
RS                679
RA                799
W                  64
OBP             0.323
SLG             0.402
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 555, dtype: object)
<class 'tuple'>
(556, Team              SFG
League             NL
Year             1992
RS                574
RA                647
W                  72
OBP             0.302
SLG             0.355
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 556, dtype: object)
<class 'tuple'>
(557, Team              STL
League             NL
Year             1992
RS                631
RA                604
W                  83
OBP             0.323
SLG             0.375
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 557, dtype: object)
<class 'tuple'>
(558, Team              TEX
League             AL
Year             1992
RS                682
RA                753
W                  77
OBP             0.321
SLG             0.393
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 558, dtype: object)
<class 'tuple'>
(559, Team              TOR
League             AL
Year             1992
RS                780
RA                682
W                  96
OBP             0.333
SLG             0.414
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 559, dtype: object)
<class 'tuple'>
(560, Team              ATL
League             NL
Year             1991
RS                749
RA                644
W                  94
OBP             0.328
SLG             0.393
BA              0.258
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 560, dtype: object)
<class 'tuple'>
(561, Team              BAL
League             AL
Year             1991
RS                686
RA                796
W                  67
OBP             0.319
SLG             0.401
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 561, dtype: object)
<class 'tuple'>
(562, Team              BOS
League             AL
Year             1991
RS                731
RA                712
W                  84
OBP              0.34
SLG             0.401
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 562, dtype: object)
<class 'tuple'>
(563, Team              CAL
League             AL
Year             1991
RS                653
RA                649
W                  81
OBP             0.314
SLG             0.374
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 563, dtype: object)
<class 'tuple'>
(564, Team              CHC
League             NL
Year             1991
RS                695
RA                734
W                  77
OBP             0.309
SLG              0.39
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 564, dtype: object)
<class 'tuple'>
(565, Team              CHW
League             AL
Year             1991
RS                758
RA                681
W                  87
OBP             0.336
SLG             0.391
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 565, dtype: object)
<class 'tuple'>
(566, Team              CIN
League             NL
Year             1991
RS                689
RA                691
W                  74
OBP              0.32
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 566, dtype: object)
<class 'tuple'>
(567, Team              CLE
League             AL
Year             1991
RS                576
RA                759
W                  57
OBP             0.313
SLG              0.35
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 567, dtype: object)
<class 'tuple'>
(568, Team              DET
League             AL
Year             1991
RS                817
RA                794
W                  84
OBP             0.333
SLG             0.416
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 568, dtype: object)
<class 'tuple'>
(569, Team              HOU
League             NL
Year             1991
RS                605
RA                717
W                  65
OBP             0.309
SLG             0.347
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 569, dtype: object)
<class 'tuple'>
(570, Team              KCR
League             AL
Year             1991
RS                727
RA                722
W                  82
OBP             0.328
SLG             0.394
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 570, dtype: object)
<class 'tuple'>
(571, Team              LAD
League             NL
Year             1991
RS                665
RA                565
W                  93
OBP             0.326
SLG             0.359
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 571, dtype: object)
<class 'tuple'>
(572, Team              MIL
League             AL
Year             1991
RS                799
RA                744
W                  83
OBP             0.336
SLG             0.396
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 572, dtype: object)
<class 'tuple'>
(573, Team              MIN
League             AL
Year             1991
RS                776
RA                652
W                  95
OBP             0.344
SLG              0.42
BA               0.28
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 573, dtype: object)
<class 'tuple'>
(574, Team              MON
League             NL
Year             1991
RS                579
RA                655
W                  71
OBP             0.308
SLG             0.357
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 574, dtype: object)
<class 'tuple'>
(575, Team              NYM
League             NL
Year             1991
RS                640
RA                646
W                  77
OBP             0.317
SLG             0.365
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 575, dtype: object)
<class 'tuple'>
(576, Team              NYY
League             AL
Year             1991
RS                674
RA                777
W                  71
OBP             0.316
SLG             0.387
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 576, dtype: object)
<class 'tuple'>
(577, Team              OAK
League             AL
Year             1991
RS                760
RA                776
W                  84
OBP             0.331
SLG             0.389
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 577, dtype: object)
<class 'tuple'>
(578, Team              PHI
League             NL
Year             1991
RS                629
RA                680
W                  78
OBP             0.303
SLG             0.358
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 578, dtype: object)
<class 'tuple'>
(579, Team              PIT
League             NL
Year             1991
RS                768
RA                632
W                  98
OBP             0.338
SLG             0.398
BA              0.263
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 579, dtype: object)
<class 'tuple'>
(580, Team              SDP
League             NL
Year             1991
RS                636
RA                646
W                  84
OBP              0.31
SLG             0.362
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 580, dtype: object)
<class 'tuple'>
(581, Team              SEA
League             AL
Year             1991
RS                702
RA                674
W                  83
OBP             0.328
SLG             0.383
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 581, dtype: object)
<class 'tuple'>
(582, Team              SFG
League             NL
Year             1991
RS                649
RA                697
W                  75
OBP             0.309
SLG             0.381
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 582, dtype: object)
<class 'tuple'>
(583, Team              STL
League             NL
Year             1991
RS                651
RA                648
W                  84
OBP             0.322
SLG             0.357
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 583, dtype: object)
<class 'tuple'>
(584, Team              TEX
League             AL
Year             1991
RS                829
RA                814
W                  85
OBP             0.341
SLG             0.424
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 584, dtype: object)
<class 'tuple'>
(585, Team              TOR
League             AL
Year             1991
RS                684
RA                622
W                  91
OBP             0.322
SLG               0.4
BA              0.257
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 585, dtype: object)
<class 'tuple'>
(586, Team              ATL
League             NL
Year             1990
RS                682
RA                821
W                  65
OBP             0.311
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN

Name: 755, dtype: object)
<class 'tuple'>
(756, Team              MON
League             NL
Year             1984
RS                593
RA                585
W                  78
OBP             0.312
SLG             0.362
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 756, dtype: object)
<class 'tuple'>
(757, Team              NYM
League             NL
Year             1984
RS                652
RA                676
W                  90
OBP              0.32
SLG             0.369
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 757, dtype: object)
<class 'tuple'>
(758, Team              NYY
League             AL
Year             1984
RS                758
RA                679
W                  87
OBP             0.339
SLG             0.404
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 758, dtype: object)
<class 'tuple'>
(759, Team              OAK
League             AL
Year             1984
RS                738
RA                796
W                  77
OBP             0.327
SLG             0.404
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 759, dtype: object)
<class 'tuple'>
(760, Team              PHI
League             NL
Year             1984
RS                720
RA                690
W                  81
OBP             0.333
SLG             0.407
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 760, dtype: object)
<class 'tuple'>
(761, Team              PIT
League             NL
Year             1984
RS                615
RA                567
W                  75
OBP              0.31
SLG             0.363
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 761, dtype: object)
<class 'tuple'>
(762, Team              SDP
League             NL
Year             1984
RS                686
RA                634
W                  92
OBP             0.317
SLG             0.371
BA              0.259
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 762, dtype: object)
<class 'tuple'>
(763, Team              SEA
League             AL
Year             1984
RS                682
RA                774
W                  74
OBP             0.324
SLG             0.384
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 763, dtype: object)
<class 'tuple'>
(764, Team              SFG
League             NL
Year             1984
RS                682
RA                807
W                  66
OBP             0.328
SLG             0.375
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 764, dtype: object)
<class 'tuple'>
(765, Team              STL
League             NL
Year             1984
RS                652
RA                645
W                  84
OBP             0.317
SLG             0.351
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 765, dtype: object)
<class 'tuple'>
(766, Team              TEX
League             AL
Year             1984
RS                656
RA                714
W                  69
OBP             0.313
SLG             0.377
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 766, dtype: object)
<class 'tuple'>
(767, Team              TOR
League             AL
Year             1984
RS                750
RA                696
W                  89
OBP             0.331
SLG             0.421
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 767, dtype: object)
<class 'tuple'>
(768, Team              ATL
League             NL
Year             1983
RS                746
RA                640
W                  88
OBP             0.341
SLG               0.4
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 768, dtype: object)
<class 'tuple'>
(769, Team              BAL
League             AL
Year             1983
RS                799
RA                652
W                  98
OBP              0.34
SLG             0.421
BA              0.269
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 769, dtype: object)
<class 'tuple'>
(770, Team              BOS
League             AL
Year             1983
RS                724
RA                775
W                  78
OBP             0.335
SLG             0.409
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 770, dtype: object)
<class 'tuple'>
(771, Team              CAL
League             AL
Year             1983
RS                722
RA                779
W                  70
OBP             0.322
SLG             0.393
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 771, dtype: object)
<class 'tuple'>
(772, Team              CHC
League             NL
Year             1983
RS                701
RA                719
W                  71
OBP             0.319
SLG             0.401
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 772, dtype: object)
<class 'tuple'>
(773, Team              CHW
League             AL
Year             1983
RS                800
RA                650
W                  99
OBP             0.329
SLG             0.413
BA              0.262
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 773, dtype: object)
<class 'tuple'>
(774, Team              CIN
League             NL
Year             1983
RS                623
RA                710
W                  74
OBP             0.314
SLG             0.356
BA              0.239
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 774, dtype: object)
<class 'tuple'>
(775, Team              CLE
League             AL
Year             1983
RS                704
RA                785
W                  70
OBP             0.338
SLG             0.369
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 775, dtype: object)
<class 'tuple'>
(776, Team              DET
League             AL
Year             1983
RS                789
RA                679
W                  92
OBP             0.335
SLG             0.427
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 776, dtype: object)
<class 'tuple'>
(777, Team              HOU
League             NL
Year             1983
RS                643
RA                646
W                  85
OBP              0.32
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 777, dtype: object)
<class 'tuple'>
(778, Team              KCR
League             AL
Year             1983
RS                696
RA                767
W                  79
OBP              0.32
SLG             0.397
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 778, dtype: object)
<class 'tuple'>
(779, Team              LAD
League             NL
Year             1983
RS                654
RA                609
W                  91
OBP             0.318
SLG             0.379
BA               0.25
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 163
OOBP              NaN
OSLG              NaN
Name: 779, dtype: object)
<class 'tuple'>
(780, Team              MIL
League             AL
Year             1983
RS                764
RA                708
W                  87
OBP             0.333
SLG             0.418
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 780, dtype: object)
<class 'tuple'>
(781, Team              MIN
League             AL
Year             1983
RS                709
RA                822
W                  70
OBP             0.319
SLG             0.401
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 781, dtype: object)
<class 'tuple'>
(782, Team              MON
League             NL
Year             1983
RS                677
RA                646
W                  82
OBP             0.326
SLG             0.386
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 782, dtype: object)
<class 'tuple'>
(783, Team              NYM
League             NL
Year             1983
RS                575
RA                680
W                  68
OBP               0.3
SLG             0.344
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 783, dtype: object)
<class 'tuple'>
(784, Team              NYY
League             AL
Year             1983
RS                770
RA                703
W                  91
OBP             0.337
SLG             0.416
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 784, dtype: object)
<class 'tuple'>
(785, Team              OAK
League             AL
Year             1983
RS                708
RA                782
W                  74
OBP             0.326
SLG             0.381
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 785, dtype: object)
<class 'tuple'>
(786, Team              PHI
League             NL
Year             1983
RS                696
RA                635
W                  90
OBP             0.329
SLG             0.373
BA              0.249
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 163
OOBP              NaN
OSLG              NaN
Name: 786, dtype: object)
<class 'tuple'>
(787, Team              PIT
League             NL
Year             1983
RS                659
RA                648
W                  84
OBP             0.325
SLG             0.383
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 787, dtype: object)
<class 'tuple'>
(788, Team              SDP
League             NL
Year             1983
RS                653
RA                653
W                  81
OBP             0.311
SLG             0.351
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 788, dtype: object)
<class 'tuple'>
(789, Team              SEA
League             AL
Year             1983
RS                558
RA                740
W                  60
OBP             0.301
SLG              0.36
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 789, dtype: object)
<class 'tuple'>
(790, Team              SFG
League             NL
Year             1983
RS                687
RA                697
W                  79
OBP             0.325
SLG             0.375
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 790, dtype: object)
<class 'tuple'>
(791, Team              STL
League             NL
Year             1983
RS                679
RA                710
W                  79
OBP             0.335
SLG             0.384
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 791, dtype: object)
<class 'tuple'>
(792, Team              TEX
League             AL
Year             1983
RS                639
RA                609
W                  77
OBP              0.31
SLG             0.366
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 792, dtype: object)
<class 'tuple'>
(793, Team              TOR
League             AL
Year             1983
RS                795
RA                726
W                  89
OBP             0.338
SLG             0.436
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 793, dtype: object)
<class 'tuple'>
(794, Team              ATL
League             NL
Year             1982
RS                739
RA                702
W                  89
OBP             0.325
SLG             0.383
BA              0.256
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 794, dtype: object)
<class 'tuple'>
(795, Team              BAL
League             AL
Year             1982
RS                774
RA                687
W                  94
OBP             0.341
SLG             0.419
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 795, dtype: object)
<class 'tuple'>
(796, Team              BOS
League             AL
Year             1982
RS                753
RA                713
W                  89
OBP              0.34
SLG             0.407
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 796, dtype: object)
<class 'tuple'>
(797, Team              CAL
League             AL
Year             1982
RS                814
RA                670
W                  93
OBP             0.347
SLG             0.433
BA              0.274
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 797, dtype: object)
<class 'tuple'>
(798, Team              CHC
League             NL
Year             1982
RS                676
RA                709
W                  73
OBP             0.317
SLG             0.375
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 798, dtype: object)
<class 'tuple'>
(799, Team              CHW
League             AL
Year             1982
RS                786
RA                710
W                  87
OBP             0.337
SLG             0.413
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 799, dtype: object)
<class 'tuple'>
(800, Team              CIN
League             NL
Year             1982
RS                545
RA                661
W                  61
OBP              0.31
SLG              0.35
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 800, dtype: object)
<class 'tuple'>
(801, Team              CLE
League             AL
Year             1982
RS                683
RA                748
W                  78
OBP             0.341
SLG             0.373
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 801, dtype: object)
<class 'tuple'>
(802, Team              DET
League             AL
Year             1982
RS                729
RA                685
W                  83
OBP             0.324
SLG             0.418
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 802, dtype: object)
<class 'tuple'>
(803, Team              HOU
League             NL
Year             1982
RS                569
RA                620
W                  77
OBP             0.302
SLG             0.349
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 803, dtype: object)
<class 'tuple'>
(804, Team              KCR
League             AL
Year             1982
RS                784
RA                717
W                  90
OBP             0.337
SLG             0.428
BA              0.285
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 804, dtype: object)
<class 'tuple'>
(805, Team              LAD
League             NL
Year             1982
RS                691
RA                612
W                  88
OBP             0.327
SLG             0.388
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 805, dtype: object)
<class 'tuple'>
(806, Team              MIL
League             AL
Year             1982
RS                891
RA                717
W                  95
OBP             0.335
SLG             0.455
BA              0.279
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 163
OOBP              NaN
OSLG              NaN
Name: 806, dtype: object)
<class 'tuple'>
(807, Team              MIN
League             AL
Year             1982
RS                657
RA                819
W                  60
OBP             0.316
SLG             0.396
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 807, dtype: object)
<class 'tuple'>
(808, Team              MON
League             NL
Year             1982
RS                697
RA                616
W                  86
OBP             0.325
SLG             0.396
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162

Name: 976, dtype: object)
<class 'tuple'>
(977, Team              CHW
League             AL
Year             1974
RS                684
RA                721
W                  80
OBP              0.33
SLG             0.389
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 977, dtype: object)
<class 'tuple'>
(978, Team              CIN
League             NL
Year             1974
RS                776
RA                631
W                  98
OBP             0.343
SLG             0.394
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 978, dtype: object)
<class 'tuple'>
(979, Team              CLE
League             AL
Year             1974
RS                662
RA                694
W                  77
OBP             0.311
SLG              0.37
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 979, dtype: object)
<class 'tuple'>
(980, Team              DET
League             AL
Year             1974
RS                620
RA                768
W                  72
OBP             0.303
SLG             0.366
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 980, dtype: object)
<class 'tuple'>
(981, Team              HOU
League             NL
Year             1974
RS                653
RA                632
W                  81
OBP             0.322
SLG             0.378
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 981, dtype: object)
<class 'tuple'>
(982, Team              KCR
League             AL
Year             1974
RS                667
RA                662
W                  77
OBP             0.327
SLG             0.364
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 982, dtype: object)
<class 'tuple'>
(983, Team              LAD
League             NL
Year             1974
RS                798
RA                561
W                 102
OBP             0.342
SLG             0.401
BA              0.272
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
Name: 983, dtype: object)
<class 'tuple'>
(984, Team              MIL
League             AL
Year             1974
RS                647
RA                660
W                  76
OBP             0.309
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 984, dtype: object)
<class 'tuple'>
(985, Team              MIN
League             AL
Year             1974
RS                673
RA                669
W                  82
OBP             0.336
SLG             0.378
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 985, dtype: object)
<class 'tuple'>
(986, Team              MON
League             NL
Year             1974
RS                662
RA                657
W                  79
OBP             0.335
SLG              0.35
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 986, dtype: object)
<class 'tuple'>
(987, Team              NYM
League             NL
Year             1974
RS                572
RA                646
W                  71
OBP             0.311
SLG             0.329
BA              0.235
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 987, dtype: object)
<class 'tuple'>
(988, Team              NYY
League             AL
Year             1974
RS                671
RA                623
W                  89
OBP             0.324
SLG             0.368
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 988, dtype: object)
<class 'tuple'>
(989, Team              OAK
League             AL
Year             1974
RS                689
RA                551
W                  90
OBP             0.321
SLG             0.373
BA              0.247
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 989, dtype: object)
<class 'tuple'>
(990, Team              PHI
League             NL
Year             1974
RS                676
RA                701
W                  80
OBP              0.32
SLG             0.373
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 990, dtype: object)
<class 'tuple'>
(991, Team              PIT
League             NL
Year             1974
RS                751
RA                657
W                  88
OBP             0.335
SLG             0.391
BA              0.274
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 991, dtype: object)
<class 'tuple'>
(992, Team              SDP
League             NL
Year             1974
RS                541
RA                830
W                  60
OBP             0.302
SLG              0.33
BA              0.229
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 992, dtype: object)
<class 'tuple'>
(993, Team              SFG
League             NL
Year             1974
RS                634
RA                723
W                  72
OBP             0.322
SLG             0.358
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 993, dtype: object)
<class 'tuple'>
(994, Team              STL
League             NL
Year             1974
RS                677
RA                643
W                  86
OBP             0.331
SLG             0.365
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 994, dtype: object)
<class 'tuple'>
(995, Team              TEX
League             AL
Year             1974
RS                690
RA                698
W                  83
OBP             0.336
SLG             0.377
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 995, dtype: object)
<class 'tuple'>
(996, Team              ATL
League             NL
Year             1973
RS                799
RA                774
W                  76
OBP             0.339
SLG             0.427
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 996, dtype: object)
<class 'tuple'>
(997, Team              BAL
League             AL
Year             1973
RS                754
RA                561
W                  97
OBP             0.345
SLG             0.389
BA              0.266
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 997, dtype: object)
<class 'tuple'>
(998, Team              BOS
League             AL
Year             1973
RS                738
RA                647
W                  89
OBP             0.338
SLG             0.401
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 998, dtype: object)
<class 'tuple'>
(999, Team              CAL
League             AL
Year             1973
RS                629
RA                657
W                  79
OBP             0.318
SLG             0.348
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 999, dtype: object)
<class 'tuple'>
(1000, Team              CHC
League             NL
Year             1973
RS                614
RA                655
W                  77
OBP              0.32
SLG             0.357
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1000, dtype: object)
<class 'tuple'>
(1001, Team              CHW
League             AL
Year             1973
RS                652
RA                705
W                  77
OBP             0.324
SLG             0.372
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1001, dtype: object)
<class 'tuple'>
(1002, Team              CIN
League             NL
Year             1973
RS                741
RA                621
W                  99
OBP             0.332
SLG             0.383
BA              0.254
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
Name: 1002, dtype: object)
<class 'tuple'>
(1003, Team              CLE
League             AL
Year             1973
RS                680
RA                826
W                  71
OBP             0.315
SLG             0.387
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1003, dtype: object)
<class 'tuple'>
(1004, Team              DET
League             AL
Year             1973
RS                642
RA                674
W                  85
OBP              0.32
SLG              0.39
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1004, dtype: object)
<class 'tuple'>
(1005, Team              HOU
League             NL
Year             1973
RS                681
RA                672
W                  82
OBP             0.312
SLG             0.376
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1005, dtype: object)
<class 'tuple'>
(1006, Team              KCR
League             AL
Year             1973
RS                755
RA                752
W                  88
OBP             0.339
SLG             0.381
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1006, dtype: object)
<class 'tuple'>
(1007, Team              LAD
League             NL
Year             1973
RS                675
RA                565
W                  95
OBP             0.323
SLG             0.371
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1007, dtype: object)
<class 'tuple'>
(1008, Team              MIL
League             AL
Year             1973
RS                708
RA                731
W                  74
OBP             0.325
SLG             0.388
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1008, dtype: object)
<class 'tuple'>
(1009, Team              MIN
League             AL
Year             1973
RS                738
RA                692
W                  81
OBP             0.342
SLG             0.393
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1009, dtype: object)
<class 'tuple'>
(1010, Team              MON
League             NL
Year             1973
RS                668
RA                702
W                  79
OBP              0.34
SLG             0.364
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1010, dtype: object)
<class 'tuple'>
(1011, Team              NYM
League             NL
Year             1973
RS                608
RA                588
W                  82
OBP             0.315
SLG             0.338
BA              0.246
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 161
OOBP              NaN
OSLG              NaN
Name: 1011, dtype: object)
<class 'tuple'>
(1012, Team              NYY
League             AL
Year             1973
RS                641
RA                610
W                  80
OBP             0.322
SLG             0.378
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1012, dtype: object)
<class 'tuple'>
(1013, Team              OAK
League             AL
Year             1973
RS                758
RA                615
W                  94
OBP             0.333
SLG             0.389
BA               0.26
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1013, dtype: object)
<class 'tuple'>
(1014, Team              PHI
League             NL
Year             1973
RS                642
RA                717
W                  71
OBP              0.31
SLG             0.371
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1014, dtype: object)
<class 'tuple'>
(1015, Team              PIT
League             NL
Year             1973
RS                704
RA                693
W                  80
OBP             0.315
SLG             0.405
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1015, dtype: object)
<class 'tuple'>
(1016, Team              SDP
League             NL
Year             1973
RS                548
RA                770
W                  60
OBP             0.296
SLG             0.351
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1016, dtype: object)
<class 'tuple'>
(1017, Team              SFG
League             NL
Year             1973
RS                739
RA                702
W                  88
OBP             0.335
SLG             0.407
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1017, dtype: object)
<class 'tuple'>
(1018, Team              STL
League             NL
Year             1973
RS                643
RA                603
W                  81
OBP             0.325
SLG             0.357
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1018, dtype: object)
<class 'tuple'>
(1019, Team              TEX
League             AL
Year             1973
RS                619
RA                844
W                  57
OBP             0.318
SLG             0.361
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1019, dtype: object)
<class 'tuple'>
(1020, Team              ATL
League             NL
Year             1971
RS                643
RA                699
W                  82
OBP             0.312
SLG             0.385
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1020, dtype: object)
<class 'tuple'>
(1021, Team              BAL
League             AL
Year             1971
RS                742
RA                530
W                 101
OBP             0.347
SLG             0.398
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 158
OOBP              NaN
OSLG              NaN
Name: 1021, dtype: object)
<class 'tuple'>
(1022, Team              BOS
League             AL
Year             1971
RS                691
RA                667
W                  85
OBP             0.322
SLG             0.397
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1022, dtype: object)
<class 'tuple'>
(1023, Team              CAL
League             AL
Year             1971
RS                511
RA                576
W                  76
OBP              0.29
SLG             0.329
BA              0.231
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1023, dtype: object)
<class 'tuple'>
(1024, Team              CHC
League             NL
Year             1971
RS                637
RA                648
W                  83
OBP             0.325
SLG             0.378
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1024, dtype: object)
<class 'tuple'>
(1025, Team              CHW
League             AL
Year             1971
RS                617
RA                597
W                  79
OBP             0.325
SLG             0.373
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1025, dtype: object)
<class 'tuple'>
(1026, Team              CIN
League             NL
Year             1971
RS                586
RA                581
W                  79
OBP               0.3
SLG             0.366
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1026, dtype: object)
<class 'tuple'>
(1027, Team              CLE
League             AL
Year             1971
RS                543
RA                747
W                  60
OBP               0.3
SLG             0.342
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1027, dtype: object)
<class 'tuple'>
(1028, Team              DET
League             AL
Year             1971
RS                701
RA                645
W                  91
OBP             0.325
SLG             0.405
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1028, dtype: object)
<class 'tuple'>
(1029, Team              HOU
League             NL
Year             1971
RS                585
RA                567
W                  79
OBP             0.302
SLG              0.34
BA               0.24
Playoffs            0

<class 'tuple'>
(1209, Team              SFG
League             NL
Year             1963
RS                725
RA                641
W                  88
OBP             0.316
SLG             0.414
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1209, dtype: object)
<class 'tuple'>
(1210, Team              STL
League             NL
Year             1963
RS                747
RA                628
W                  93
OBP             0.326
SLG             0.403
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1210, dtype: object)
<class 'tuple'>
(1211, Team              WSA
League             AL
Year             1963
RS                578
RA                812
W                  56
OBP             0.293
SLG             0.351
BA              0.227
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1211, dtype: object)
<class 'tuple'>
(1212, Team              BAL
League             AL
Year             1962
RS                652
RA                680
W                  77
OBP             0.314
SLG             0.387
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1212, dtype: object)
<class 'tuple'>
(1213, Team              BOS
League             AL
Year             1962
RS                707
RA                756
W                  76
OBP             0.324
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
Name: 1213, dtype: object)
<class 'tuple'>
(1214, Team              CHC
League             NL
Year             1962
RS                632
RA                827
W                  59
OBP             0.317
SLG             0.377
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1214, dtype: object)
<class 'tuple'>
(1215, Team              CHW
League             AL
Year             1962
RS                707
RA                658
W                  85
OBP             0.334
SLG             0.372
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1215, dtype: object)
<class 'tuple'>
(1216, Team              CIN
League             NL
Year             1962
RS                802
RA                685
W                  98
OBP             0.332
SLG             0.417
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1216, dtype: object)
<class 'tuple'>
(1217, Team              CLE
League             AL
Year             1962
RS                682
RA                745
W                  80
OBP             0.312
SLG             0.388
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1217, dtype: object)
<class 'tuple'>
(1218, Team              DET
League             AL
Year             1962
RS                758
RA                692
W                  85
OBP              0.33
SLG             0.411
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1218, dtype: object)
<class 'tuple'>
(1219, Team              HOU
League             NL
Year             1962
RS                592
RA                717
W                  64
OBP              0.31
SLG             0.351
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1219, dtype: object)
<class 'tuple'>
(1220, Team              KCA
League             AL
Year             1962
RS                745
RA                837
W                  72
OBP             0.332
SLG             0.386
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1220, dtype: object)
<class 'tuple'>
(1221, Team              LAA
League             AL
Year             1962
RS                718
RA                706
W                  86
OBP             0.325
SLG              0.38
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1221, dtype: object)
<class 'tuple'>
(1222, Team              LAD
League             NL
Year             1962
RS                842
RA                697
W                 102
OBP             0.337
SLG               0.4
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 165
OOBP              NaN
OSLG              NaN
Name: 1222, dtype: object)
<class 'tuple'>
(1223, Team              MIN
League             AL
Year             1962
RS                798
RA                713
W                  91
OBP             0.338
SLG             0.412
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 1223, dtype: object)
<class 'tuple'>
(1224, Team              MLN
League             NL
Year             1962
RS                730
RA                665
W                  86
OBP             0.326
SLG             0.403
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1224, dtype: object)
<class 'tuple'>
(1225, Team              NYM
League             NL
Year             1962
RS                617
RA                948
W                  40
OBP             0.318
SLG             0.361
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1225, dtype: object)
<class 'tuple'>
(1226, Team              NYY
League             AL
Year             1962
RS                817
RA                680
W                  96
OBP             0.337
SLG             0.426
BA              0.267
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
Name: 1226, dtype: object)
<class 'tuple'>
(1227, Team             PHI
League            NL
Year            1962
RS               705
RA               759
W                 81
OBP             0.33
SLG             0.39
BA              0.26
Playoffs           0
RankSeason       NaN
RankPlayoffs     NaN
G                161
OOBP             NaN
OSLG             NaN
Name: 1227, dtype: object)
<class 'tuple'>
(1228, Team              PIT
League             NL
Year             1962
RS                706
RA                626
W                  93
OBP             0.321
SLG             0.394
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
Name: 1228, dtype: object)
<class 'tuple'>
(1229, Team              SFG
League             NL
Year             1962
RS                878
RA                690
W                 103
OBP             0.341
SLG             0.441
BA              0.278
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 165
OOBP              NaN
OSLG              NaN
Name: 1229, dtype: object)
<class 'tuple'>
(1230, Team              STL
League             NL
Year             1962
RS                774
RA                664
W                  84
OBP             0.335
SLG             0.394
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
Name: 1230, dtype: object)
<class 'tuple'>
(1231, Team              WSA
League             AL
Year             1962
RS                599
RA                716
W                  60
OBP             0.308
SLG             0.373
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
Name: 1231, dtype: object)
<class 'tuple'>

### Run differentials with .iterrows()

In [57]:
# Create an empty list to store run differentials
run_diffs = []

def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

# Write a for loop and collect runs allowed and runs scored for each row
for i,row in pit_df.iterrows():
    runs_scored = row['RS']
    runs_allowed = row['RA']
    
    # Use the provided function to calculate run_diff for each row
    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    # Append each run differential to the output list
    run_diffs.append(run_diff)

pit_df['RD'] = run_diffs
pit_df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,RD
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,46
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,100
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,7
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,-72
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,-146

### Iterating with .itertuples()

In [58]:
# Loop over the DataFrame and print each row's Index, Year and Wins (W)
for row in pit_df.itertuples():
    i = row.Index
    year = row.Year
    wins = row.W
  
  # Check if rangers made Playoffs (1 means yes; 0 means no)
    if row.Playoffs == 1:
        print(i, year, wins)

1 2012 94
2 2012 93
6 2012 97
9 2012 88
18 2012 95
19 2012 94
24 2012 94
25 2012 88
27 2012 93
29 2012 98
30 2011 94
39 2011 95
45 2011 96
48 2011 97
50 2011 102
55 2011 90
56 2011 91
57 2011 96
61 2010 91
66 2010 91
76 2010 94
78 2010 95
80 2010 97
84 2010 92
86 2010 96
87 2010 90
93 2009 95
98 2009 92
103 2009 97
104 2009 95
106 2009 87
108 2009 103
110 2009 93
115 2009 91
123 2008 95
124 2008 97
125 2008 89
133 2008 100
134 2008 84
135 2008 90
140 2008 92
146 2008 97
150 2007 90
153 2007 96
154 2007 85
157 2007 96
158 2007 90
163 2007 94
168 2007 94
170 2007 89
189 2006 95
194 2006 88
196 2006 96
197 2006 97
198 2006 97
199 2006 93
202 2006 88
205 2006 83
211 2005 90
213 2005 95
215 2005 99
221 2005 89
223 2005 95
228 2005 95
232 2005 82
235 2005 100
240 2004 92
242 2004 96
244 2004 98
252 2004 92
254 2004 93
256 2004 92
259 2004 101
266 2004 105
272 2003 101
274 2003 95
275 2003 88
281 2003 91
286 2003 90
289 2003 101
290 2003 96
295 2003 100
300 2002 99
301 2002 98
302 2002 101
316 2002 94
319 2002 103
320 2002 103
325 2002 95
326 2002 97
331 2001 92
332 2001 88
338 2001 91
342 2001 93
349 2001 95
350 2001 102
354 2001 116
356 2001 93
362 2000 95
366 2000 95
378 2000 94
379 2000 87
380 2000 91
384 2000 91
385 2000 97
386 2000 95
391 1999 100
392 1999 103
394 1999 94
398 1999 97
402 1999 97
408 1999 97
409 1999 98
418 1999 95
422 1998 106
424 1998 92
425 1998 90
428 1998 89
432 1998 102
439 1998 114
443 1998 98
448 1998 88
451 1997 101
452 1997 98
457 1997 86
460 1997 92
461 1997 84
468 1997 96
473 1997 90
474 1997 90
478 1996 96
479 1996 88
485 1996 99
491 1996 90
496 1996 92
500 1996 91
503 1996 88
504 1996 90
506 1993 104
511 1993 94
526 1993 97
533 1993 95
534 1992 98
551 1992 96
553 1992 96
559 1992 96
560 1991 94
573 1991 95
579 1991 98
585 1991 91
588 1990 88
592 1990 91
603 1990 103
605 1990 95
616 1989 93
629 1989 99
634 1989 92
637 1989 89
640 1988 89
649 1988 94
653 1988 100
655 1988 104
672 1987 98
677 1987 85
686 1987 90
687 1987 95
692 1986 95
693 1986 92
699 1986 96
705 1986 108
726 1985 91
727 1985 95
739 1985 101
741 1985 99
746 1984 96
750 1984 104
752 1984 84
762 1984 92
769 1983 98
773 1983 99
779 1983 91
786 1983 90
794 1982 89
797 1982 93
806 1982 95
817 1982 92
829 1980 93
830 1980 97
836 1980 103
838 1980 91
847 1979 102
849 1979 88
852 1979 90
865 1979 98
882 1978 92
883 1978 95
888 1978 100
890 1978 90
908 1977 102
909 1977 98
914 1977 100
916 1977 101
930 1976 102
934 1976 90
940 1976 97
942 1976 101
950 1975 95
954 1975 108
965 1975 98
967 1975 92
973 1974 91
983 1974 102
989 1974 90
991 1974 88
997 1973 97
1002 1973 99
1011 1973 82
1013 1973 94
1021 1971 101
1037 1971 101
1039 1971 97
1041 1971 90
1045 1970 108
1050 1970 102
1057 1970 98
1063 1970 89
1068 1969 93
1069 1969 109
1080 1969 97
1082 1969 100
1100 1968 103
1110 1968 97
1114 1967 92
1130 1967 101
1133 1966 97
1143 1966 95
1162 1965 97
1163 1965 102
1186 1964 99
1190 1964 93
1202 1963 99
1206 1963 104
1226 1962 96
1229 1962 103

### Run differentials with .itertuples()

In [60]:
run_diffs = []

# Loop over the DataFrame and calculate each row's run differential
for row in pit_df.itertuples():
    
    runs_scored = row.RS
    runs_allowed = row.RA

    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    run_diffs.append(run_diff)

# Append new column
pit_df['RD'] = run_diffs
pit_df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,RD
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,46
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,100
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,7
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,-72
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,-146

### Analyzing baseball stats with .apply()

In [63]:
# Gather total runs scored in all games per year
total_runs_scored = pit_df[['RS', 'RA']].apply(sum, axis=1)
total_runs_scored.head()

0    1422
1    1300
2    1417
3    1540
4    1372
dtype: int64

In [65]:
def text_playoffs(num_playoffs): 
    if num_playoffs == 1:
        return 'Yes'
    else:
        return 'No' 
    
# Convert numeric playoffs to text
textual_playoffs = pit_df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)
textual_playoffs.head()

0     No
1    Yes
2    Yes
3     No
4     No
dtype: object

### Settle a debate with .apply()

In [70]:
def calc_win_perc(wins, games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)

# Display the first five rows of the DataFrame
display(pit_df.head())

# Create a win percentage Series 
win_percs = pit_df.apply(lambda row: calc_win_perc(row['W'], row['G']), axis=1)
display(win_percs.head(), '\n')

# Append a new column to dbacks_df
pit_df['WP'] = win_percs
display(pit_df.head(), '\n')

# Display dbacks_df where WP is greater than 0.50
display(pit_df[pit_df['WP'] >= 0.50])

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,RD,WP
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,46,0.50
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,100,0.58
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,7,0.57
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,-72,0.43
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,-146,0.38

0    0.50
1    0.58
2    0.57
3    0.43
4    0.38
dtype: float64

'\n'

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,RD,WP
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,46,0.50
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,100,0.58
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,7,0.57
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,-72,0.43
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,-146,0.38

'\n'

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,RD,WP
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,46,0.50
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,100,0.58
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,7,0.57
5,CHW,AL,2012,748,676,85,0.318,0.422,0.255,0,NaN,NaN,162,0.319,0.405,72,0.52
6,CIN,NL,2012,669,588,97,0.315,0.411,0.251,1,2.0,4.0,162,0.305,0.390,81,0.60
9,DET,AL,2012,726,670,88,0.335,0.422,0.268,1,6.0,2.0,162,0.314,0.402,56,0.54
12,LAA,AL,2012,767,699,89,0.332,0.433,0.274,0,NaN,NaN,162,0.310,0.403,68,0.55
13,LAD,NL,2012,637,597,86,0.317,0.374,0.252,0,NaN,NaN,162,0.310,0.364,40,0.53
15,MIL,NL,2012,776,733,83,0.325,0.437,0.259,0,NaN,NaN,162,0.326,0.414,43,0.51
18,NYY,AL,2012,804,668,95,0.337,0.453,0.265,1,3.0,3.0,162,0.311,0.419,136,0.59
19,OAK,AL,2012,713,614,94,0.310,0.404,0.238,1,4.0,4.0,162,0.306,0.378,99,0.58
20,PHI,NL,2012,684,680,81,0.317,0.400,0.255,0,NaN,NaN,162,0.306,0.407,4,0.50
24,SFG,NL,2012,718,649,94,0.327,0.397,0.269,1,4.0,1.0,162,0.313,0.393,69,0.58
25,STL,NL,2012,765,648,88,0.338,0.421,0.271,1,6.0,3.0,162,0.313,0.387,117,0.54
26,TBR,AL,2012,697,577,90,0.317,0.394,0.240,0,NaN,NaN,162,0.294,0.352,120,0.56
27,TEX,AL,2012,808,707,93,0.334,0.446,0.273,1,5.0,5.0,162,0.309,0.408,101,0.57
29,WSN,NL,2012,731,594,98,0.322,0.428,0.261,1,1.0,4.0,162,0.303,0.373,137,0.60
30,ARI,NL,2011,731,662,94,0.322,0.413,0.250,1,5.0,4.0,162,0.316,0.409,69,0.58
31,ATL,NL,2011,641,605,89,0.308,0.387,0.243,0,NaN,NaN,162,0.310,0.361,36,0.55
33,BOS,AL,2011,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392,138,0.56
39,DET,AL,2011,787,711,95,0.340,0.434,0.277,1,4.0,3.0,162,0.321,0.396,76,0.59
43,LAA,AL,2011,667,633,86,0.313,0.402,0.253,0,NaN,NaN,162,0.313,0.388,34,0.53
44,LAD,NL,2011,644,612,82,0.322,0.375,0.257,0,NaN,NaN,161,0.310,0.371,32,0.51
45,MIL,NL,2011,721,638,96,0.325,0.425,0.261,1,3.0,3.0,162,0.304,0.385,83,0.59
48,NYY,AL,2011,867,657,97,0.343,0.444,0.263,1,2.0,4.0,162,0.322,0.399,210,0.60
50,PHI,NL,2011,713,529,102,0.323,0.395,0.253,1,1.0,4.0,162,0.296,0.361,184,0.63
54,SFG,NL,2011,570,578,86,0.303,0.368,0.242,0,NaN,NaN,162,0.309,0.346,-8,0.53
55,STL,NL,2011,762,692,90,0.341,0.425,0.273,1,7.0,1.0,162,0.319,0.398,70,0.56
56,TBR,AL,2011,707,614,91,0.322,0.402,0.244,1,6.0,4.0,162,0.303,0.383,93,0.56
57,TEX,AL,2011,855,677,96,0.340,0.460,0.283,1,3.0,2.0,162,0.307,0.392,178,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,DET,AL,1964,699,678,85,0.319,0.395,0.253,0,NaN,NaN,163,NaN,NaN,21,0.52
1181,LAA,AL,1964,544,551,82,0.304,0.344,0.242,0,NaN,NaN,162,NaN,NaN,-7,0.51
1184,MLN,NL,1964,803,744,88,0.333,0.418,0.272,0,NaN,NaN,162,NaN,NaN,59,0.54
1186,NYY,AL,1964,730,577,99,0.317,0.387,0.253,1,1.0,2.0,164,NaN,NaN,153,0.60
1187,PHI,NL,1964,693,632,92,0.315,0.391,0.258,0,NaN,NaN,162,NaN,NaN,61,0.57
1189,SFG,NL,1964,656,587,90,0.310,0.382,0.246,0,NaN,NaN,162,NaN,NaN,69,0.56
1190,STL,NL,1964,715,652,93,0.324,0.392,0.272,1,2.0,1.0,162,NaN,NaN,63,0.57
1192,BAL,AL,1963,644,621,86,0.310,0.380,0.249,0,NaN,NaN,162,NaN,NaN,23,0.53
1194,CHC,NL,1963,570,578,82,0.297,0.363,0.238,0,NaN,NaN,162,NaN,NaN,-8,0.51
1195,CHW,AL,1963,683,544,94,0.323,0.365,0.250,0,NaN,NaN,162,NaN,NaN,139,0.58
1196,CIN,NL,1963,648,594,86,0.310,0.371,0.246,0,NaN,NaN,162,NaN,NaN,54,0.53
1202,LAD,NL,1963,640,550,99,0.309,0.357,0.251,1,2.0,1.0,163,NaN,NaN,90,0.61
1203,MIN,AL,1963,767,602,91,0.325,0.430,0.255,0,NaN,NaN,161,NaN,NaN,165,0.57
1204,MLN,NL,1963,677,603,84,0.312,0.370,0.244,0,NaN,NaN,163,NaN,NaN,74,0.52
1206,NYY,AL,1963,714,547,104,0.309,0.403,0.252,1,1.0,2.0,161,NaN,NaN,167,0.65
1207,PHI,NL,1963,642,578,87,0.306,0.381,0.252,0,NaN,NaN,162,NaN,NaN,64,0.54
1209,SFG,NL,1963,725,641,88,0.316,0.414,0.258,0,NaN,NaN,162,NaN,NaN,84,0.54
1210,STL,NL,1963,747,628,93,0.326,0.403,0.271,0,NaN,NaN,162,NaN,NaN,119,0.57
1215,CHW,AL,1962,707,658,85,0.334,0.372,0.257,0,NaN,NaN,162,NaN,NaN,49,0.52
1216,CIN,NL,1962,802,685,98,0.332,0.417,0.270,0,NaN,NaN,162,NaN,NaN,117,0.60
1218,DET,AL,1962,758,692,85,0.330,0.411,0.248,0,NaN,NaN,161,NaN,NaN,66,0.53
1221,LAA,AL,1962,718,706,86,0.325,0.380,0.250,0,NaN,NaN,162,NaN,NaN,12,0.53
1222,LAD,NL,1962,842,697,102,0.337,0.400,0.268,0,NaN,NaN,165,NaN,NaN,145,0.62
1223,MIN,AL,1962,798,713,91,0.338,0.412,0.260,0,NaN,NaN,163,NaN,NaN,85,0.56
1224,MLN,NL,1962,730,665,86,0.326,0.403,0.252,0,NaN,NaN,162,NaN,NaN,65,0.53
1226,NYY,AL,1962,817,680,96,0.337,0.426,0.267,1,2.0,1.0,162,NaN,NaN,137,0.59
1227,PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN,-54,0.50
1228,PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN,80,0.58
1229,SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN,188,0.62
1230,STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN,110,0.52

### Replacing .iloc with underlying arrays

In [71]:
# Use the W array and G array to calculate win percentages
win_percs_np = calc_win_perc(pit_df['W'].values, pit_df['G'].values)

# Append a new column to baseball_df that stores all win percentages
pit_df['WP'] = win_percs_np 

print(pit_df.head())

  Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN

   RankPlayoffs    G   OOBP   OSLG   RD    WP
0           NaN  162  0.317  0.415   46  0.50
1           5.0  162  0.306  0.378  100  0.58
2           4.0  162  0.315  0.403    7  0.57
3           NaN  162  0.331  0.428  -72  0.43
4           NaN  162  0.335  0.424 -146  0.38

### Bringing it all together: Predict win percentage

In [73]:
win_perc_preds_loop = []

def predict_win_perc(RS, RA):
    prediction = RS ** 2 / (RS ** 2 + RA ** 2)
    return np.round(prediction, 2)

# Use a loop and .itertuples() to collect each row's predicted win percentage
for row in pit_df.itertuples():
    runs_scored = row.RS
    runs_allowed = row.RA
    win_perc_pred = predict_win_perc(runs_scored, runs_allowed)
    win_perc_preds_loop.append(win_perc_pred)

# Apply predict_win_perc to each row of the DataFrame
win_perc_preds_apply = pit_df.apply(lambda row: predict_win_perc(row['RS'], row['RA']), axis=1)

# Calculate the win percentage predictions using NumPy arrays
win_perc_preds_np = predict_win_perc(pit_df['RS'].values, pit_df["RA"].values)
pit_df['WP_preds'] = win_perc_preds_np
print(pit_df.head())

  Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN

   RankPlayoffs    G   OOBP   OSLG   RD    WP  WP_preds
0           NaN  162  0.317  0.415   46  0.50      0.53
1           5.0  162  0.306  0.378  100  0.58      0.58
2           4.0  162  0.315  0.403    7  0.57      0.50
3           NaN  162  0.331  0.428  -72  0.43      0.45
4           NaN  162  0.335  0.424 -146  0.38      0.39